---
title: "Quarterly Performance Report"
output: 
  powerpoint_presentation:
    reference_doc: template.pptx
---


```{r Load Packages, echo = FALSE, warning = FALSE, message = FALSE}

# Load packages -----------------------------------------------------------------------------------
suppressMessages({
  memory.limit(size = 8000000)
  library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  library(zipcodeR)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(feather)
  # library(zipcodeR)
  library(formattable)
  library(shinyjs)
  library(janitor)
  library(patchwork)
  library(flexdashboard)
  # library(tidyverse)
  # library(viridis)
  # library(hrbrthemes)
  # library(plotly)
  # install.packages("bsts")
  library(bsts)
  library(reactable)
  # install.packages("reactablefmtr")
  library(reactablefmtr)
  library(svDialogs)
  library(openxlsx)
  library(flextable)
  library(officedown)
  library(officer)
  library(magrittr)
  library(webshot) 
  library(png)
  library(ggh4x)
})

```


```{r Graph asthetics, echo = FALSE, warning = FALSE, message = FALSE}
### Color Functions for Graphs ============================================================

# Mount Sinai corporate colors "USE THIS TO ADD COLORS"
MountSinai_colors <- c(
  `dark purple`  = "#212070",
  `dark pink`    = "#d80b8c",
  `dark blue`    = "#00aeef",
  `dark grey`    = "#7f7f7f",
  `yellow`       = "#ffc000",
  `purple`       = "#7030a0",
  `med purple`   = "#5753d0",
  `med pink`     = "#f75dbe",
  `med blue`     = "#5cd3ff",
  `med grey`     = "#a5a7a5",
  `light purple` = "#c7c6ef",
  `light pink`   = "#fcc9e9",
  `light blue`   = "#c9f0ff",
  `light grey`   = "#dddedd"
  )

# Function to extract Mount Sinai colors as hex codes
# Use Character names of MountSinai_colors

MountSinai_cols <- function(...) {
  cols <- c(...)
  
  if (is.null(cols))
    return (MountSinai_colors)
  
  MountSinai_colors[cols]
}

# Color Function that can be used to call all colors is "MountSinai_cols()"
# Use in ggplot 

  #MountSinai_cols()       # will provide all colors and their hex codes in a table 
  #MountSinai_cols("pink") # will provide color name and the hex code for the pink color

# Create palettes 
MountSinai_palettes <- list(
  `all`   = MountSinai_cols("dark purple","dark pink","dark blue","dark grey",
                            "med purple","med pink","med blue","med grey", 
                            "light purple","light pink","light blue","light grey"),
  
  `main`  = MountSinai_cols("dark purple","dark pink","dark blue","dark grey"),
  
  `purple`  = MountSinai_cols("dark purple","med purple","light purple"),
  
  `pink`  = MountSinai_cols("dark pink","med pink","light pink"),
  
  `blue`  = MountSinai_cols("dark blue", "med blue", "light blue"),
  
  `grey`  = MountSinai_cols("dark grey", "med grey", "light grey"),
  
  `purpleGrey` = MountSinai_cols("dark purple", "dark grey"),
  
  `pinkBlue` = MountSinai_cols("dark pink", "dark blue")
  
)

# MountSinai_palettes
# Return function to interpolate a Mount Sinai color palette
# default value is the main palette, reverse = True will change the order

MountSinai_pal <- function(palette = "all", reverse = FALSE, ...) {
  pal <- MountSinai_palettes[[palette]]
  
  if (reverse) pal <- rev(pal)
  
  colorRampPalette(pal, ...)
}



# Scale Function for ggplot can be used instead of scale_color_manual
scale_color_MountSinai <- function(palette = "all", discrete = TRUE, reverse = FALSE, ...) {
  pal <- MountSinai_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("colour", paste0("MountSinai_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}

# Scale Fill for ggplot insetead of scale_fill_manual 
scale_fill_MountSinai <- function(palette = "all", discrete = TRUE, reverse = FALSE, ...) {
  pal <- MountSinai_pal(palette = palette, reverse = reverse)

  if (discrete) {
    discrete_scale("fill", paste0("MountSinai_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}

# Use in ggplot 
  # scale_color_MountSinai("main")

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

<style>
.table {
table-layout: fixed;
width: 100%;
}
</style>

```{r Global Functions, echo = FALSE, warning = FALSE, message = FALSE}

'%!in%' <- function(x,y)!('%in%'(x,y)) # Does not include
not_all_na <- function(x) all(!is.na(x)) # Exclude columns with All NAs

```


```{r Import Scheduling and Utilization Data, echo = FALSE, warning = FALSE, message = FALSE}

# Specify campuses to include
# inc_sites <- c("NETWORK","MSM","MSH-MSDFP","ONCOLOGY","MSW","MSBI","MSUS","MSH- AMBULATORY CARE","MSDD")

# Import in scheduling data ----------------------------------------------------
# scheduling_data_raw <- as.data.frame(read_rds(file.choose())) 
# scheduling_data_raw <- scheduling_data_raw %>%
#   mutate(Appt.WeekNum = lubridate::epiweek(Appt.DateYear),
#          Appt.YearQtr = as.yearqtr(Appt.DTTM),
#          Appt.Made.YearQtr = as.yearqtr(Appt.Made.DTTM),
#          Visit.Method  = case_when(Visit.Method == "IN PERSON" ~ 'IN PERSON',TRUE ~ 'TELEHEALTH'),
#          New.PT2 = case_when(New.PT2 == "TRUE" ~ 'New',TRUE ~ 'Established'),
#          Appt.Made.DateYear = as.Date(Appt.Made.DTTM, format="%Y-%m-%d"),
#          Appt.Made.MonthYear = format(as.Date(Appt.Made.DTTM, format="%m/%d/%Y"), "%Y-%m"),
#          Appt.Made.Year = format(as.Date(Appt.Made.DTTM, format="%m/%d/%Y"), "%Y"),
#          Appt.Made.WeekNum = as.numeric(strftime(Appt.Made.DTTM, format = "%V"))) 
# 
# scheduling_data_raw <- scheduling_data_raw %>% filter(Campus %in% inc_sites)
# 
# # Import in utilization data ---------------------------------------------------
# util_data_raw <- as.data.frame(read_rds(file.choose())) %>%
#   filter(Appt.Status == "Arrived") %>%
#   filter(Appt.DateYear <= Sys.Date()) 
# 
# util_data_raw$Appt.YearQtr <- as.yearqtr(util_data_raw$Appt.DateYear) 
# 
# ## Add Session Column to Scheduling and Utilization
# scheduling_data_raw$Session <- ifelse(as.integer(sub(':.*', '', scheduling_data_raw$Time)) >= 12, 'PM', 'AM') 
# util_data_raw$Session <- ifelse(as.integer(sub(':.*', '', util_data_raw$Appt.TM.Hr)) >= 12, 'PM', 'AM') 

```

```{r Import Global Mapping Files, echo = FALSE, warning = FALSE, message = FALSE}

# Import Department Zip Code Data (Epic Department Zip Code Mapping) -----------
# dept_zip_code_ref <- read_csv("Department_Zip_Code.csv")
# visitPlan <- read_csv(file.choose())


# Map Visit Plan in scheduling data
# scheduling_data_raw$Coverage <- visitPlan$VisitPlan_Group[match(scheduling_data_raw$VISITPLAN, visitPlan$VISITPLAN)]

```


```{r Import Room Inventory Data, echo = FALSE, warning = FALSE, message = FALSE}

# # Import Room Count Summary by Specialty and Site 
# room_count_raw <- read_excel("ENT_Room_Count_Summary.xlsx")
# room_count_raw <- room_count_raw %>%
#   filter(!is.na(`Room Count`)) 
# 
# room_count_summary_site <- room_count_raw %>%
#   group_by(Campus.Specialty, Campus, Benchmark) %>%
#   summarise(room_count = sum(`Room Count`))
# 
# room_count_summary_mshs <- room_count_raw %>%
#   group_by(Campus.Specialty, Benchmark) %>%
#   summarise(room_count = sum(`Room Count`),
#             Benchmark = mean(Benchmark ))

```


```{r Quarterly Processed Data Files, echo = FALSE, warning = FALSE, message = FALSE}

# Referrals Tables -------------------------------------------------------------
monthly_referral_vol <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/monthly_referral_vol.rds")

# Volume Tables ----------------------------------------------------------------
## Arrived monthly volume ======================================================
monthly_vol <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/monthly_vol.rds")
## Arrived Epic department quarterly volume ====================================
vol_zip_code <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/vol_zip_code.rds")

# Access Tables ----------------------------------------------------------------
## Wait Time Horizon by Specialty ==============================================
waitTime_dist_specialty <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/waitTime_dist_specialty.rds")
waitTime_dist_site <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/waitTime_dist_site.rds")
                                   
## Median Wait Time ============================================================
waitTime_mshs <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/waitTime_mshs.rds")
waitTime_site <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/waitTime_site.rds")
waitTime_prov <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/waitTime_prov.rds")

# Payor Mix Table --------------------------------------------------------------
payer_mix_quarter_site <- readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/Quarterly_Data/payer_mix_quarter_site.rds")


# # Utilization Data -------------------------------------------------------------
# ## Location=====================================================================
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/locations_util_turns_merged.rds") # By Turns
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/locations_util_turns_summary.rds") # By Turns
# 
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/locations_util_dur_merged.rds") # By Durations
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/locations_util_dur_summary.rds") # By Durations
# 
# ## Provider ====================================================================
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/provider_util_turns_summary.rds") # By Turns
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/provider_util_dur_summary.rds") # By Turns
# readRDS("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/quarterly-processing/provider_util_dur_merged.rds") # By Turns

```

```{r Data Processing, echo = FALSE, warning = FALSE, message = FALSE}

monthly_vol <- monthly_vol %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup))) 

vol_zip_code <- vol_zip_code %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup))) 

waitTime_dist_specialty <- waitTime_dist_specialty %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup)))

waitTime_dist_site <- waitTime_dist_site %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup))) 

waitTime_mshs <- waitTime_mshs %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup)))

waitTime_site <- waitTime_site %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup))) 

monthly_referral_vol <- monthly_referral_vol %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup)))

waitTime_prov <- waitTime_prov %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup)))

payer_mix_quarter_site <- payer_mix_quarter_site %>%
  mutate(Specialty = ifelse(is.na(Campus.Specialty.SubGroup), Campus.Specialty.Group, 
                                paste0(Campus.Specialty.Group, " - ",Campus.Specialty.SubGroup)))

```


```{r Global Variables, echo = FALSE, warning = FALSE, message = FALSE}

quarter_start <- "2021-01-01"
quarter_end <- "2022-07-01"

quarters_list <- sort(unique(as.yearqtr(seq(from=as.Date(quarter_start) , to=floor_date(as.Date(quarter_end) -1 - months(1), "month"), by="month"))))

# reporting_date <- max((scheduling_data_raw %>% filter(Appt.Status == "Arrived") %>% filter(Appt.DateYear <= Sys.Date()))$Appt.DateYear)
reporting_year <- format(quarters_list[length(quarters_list)], "%Y") ## Create year column
reporting_YearQtr <- quarters_list[length(quarters_list)]

data_quarters <- tail(quarters_list,5)

# Specify campuses to include
inc_sites <- c("NETWORK","MSM","MSH-MSDFP","ONCOLOGY","MSW","MSBI","MSUS","MSH- AMBULATORY CARE","MSDD")

```


```{r Productivity Data Import, echo = FALSE, warning = FALSE, message = FALSE}

productivity_raw <- read_excel("C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/performance-report/All Productivity 2021-Jun 2022 by dept.xlsx")
productivity_raw <- productivity_raw %>%
  filter(`Master Dept` %!in% c("BIMG","MS DOCS","West Care/ West Park","HUDSON YARDS","MANHASSET")) %>%
  filter(!is.na(`Master Dept`)) %>%
  mutate(NPI = as.character(NPI)) %>%
  pivot_longer(17:length(productivity_raw),
               names_to = "Quarter",
               values_to = "Productivity") %>%
  mutate(Quarter = as.yearqtr(Quarter))

waitTime_prov <- merge(waitTime_prov, 
                       productivity_raw[,c("NPI", "Quarter", "Productivity")],
                       by.x = c("NPI", "Appt.Made.YearQtr"),
                       by.y = c("NPI", "Quarter"), all.x = TRUE, all.y = FALSE)

productivity_raw <- merge(productivity_raw,
                         waitTime_prov[,c("NPI", "Appt.Made.YearQtr", "Campus", "Specialty", "med_wait")],
                          by.x = c("NPI", "Quarter"),
                          by.y = c("NPI", "Appt.Made.YearQtr"))
productivity_raw <- productivity_raw %>%
  arrange(Productivity)
  

```



```{r Reactable Theme, echo = FALSE, warning = FALSE, message = FALSE}

# Flextable Custom Theme
theme_design <- function(x) {
  x <- border_remove(x)
  x <- fontsize(x, size = 10, part = "all")
  x <- font(x, fontname = "Calibri", part = "all")
  x <- align(x, align = "center", part = "all")
  x <- align(x, align = "left", part = "footer")
  x <- bold(x, bold = TRUE, part = "header")
  x <- color(x, color = "white", part = "header")
  x <- padding(x, padding = 6, part = "all")
  x <- border_inner_h(x, border = fp_border_default(width = 1, color = "white"), part="all")
  x <- border_inner_v(x, border =fp_border_default(width = 4, color = "white"), part="all")
  x <- set_table_properties(x, layout = "fixed")
  x
}

# Heat Map Conditional Formatting Example 
# colourer <- col_numeric(
#   palette = c("wheat", "red"),
#   domain = c(0, 1))
# 
# bg(ft_2, 
#     i = 1:2,
#     j = c("Sepal.Length", "Sepal.Width",
#           "Petal.Length", "Petal.Width"),
#     bg = colourer)

```


```{r Monthly Volume Graph Output, echo = FALSE, warning = FALSE, message = FALSE}

dept_monthly_vol_function <- function(department){
  # department <- "Dermatology"
  dept_vol <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Visit.Method != "Total") %>%
    filter(Appt.YearQtr %in% data_quarters) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Campus.Specialty.Group, Appt.YearQtr, Appt.Month, Visit.Method) %>%
    summarise(monthly_vol = sum(monthly_vol)) %>%
    mutate(perc = percent(monthly_vol/sum(monthly_vol),0))
  
  
  monthOptions <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
  
  ggplot(dept_vol, aes(x= factor(Appt.Month, levels = monthOptions),
                       y=monthly_vol, group=Visit.Method, fill=Visit.Method))+
    geom_bar(position="stack",stat="identity", width=0.7)+
    facet_grid(.~Appt.YearQtr, scales = "free", space = "free_x") + 
    scale_fill_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000","#7030a0","#5753d0","#5cd3ff"))+
    scale_y_continuous(limits=c(0, max((dept_vol %>% group_by(Appt.YearQtr, Appt.Month) %>% summarise(total = sum(monthly_vol)))$total)*1.1), 
                       labels = scales::number_format(accuracy = 1),
                       expand = c(0,0))+
    labs(title = "Ambulatory Visit Volume",
         subtitle = department,
         x = NULL, y = NULL, fill = "Site")+
    theme_bw()+
    theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
            plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
            legend.position = "bottom",
            legend.text = element_text(size="8"),
            legend.direction = "horizontal",
            legend.title = element_blank(),
            axis.title = element_blank(),
            axis.text = element_text(size="10"),
            axis.title.x = element_blank(),
            axis.line = element_line(size = 0.3, colour = "black"))+
    geom_text(aes(label=paste0(prettyNum(monthly_vol, big.mark = ','),"\n","(",perc,")")), color="white", 
                size=2, fontface="bold", position = position_stack(vjust = 0.5))+
    stat_summary(fun.y = sum, vjust = -1, aes(label=ifelse(..y.. == 0,"",prettyNum(..y.., big.mark = ',')), group = Appt.Month), geom="text", color="black", 
                 size=3)+
    guides(fill = guide_legend(nrow = 1))
    
}


# dept_monthly_vol_function_sub <- function(department){
#   
#   dept_vol <- monthly_vol %>%
#     filter(Specialty == department) %>%
#     filter(Visit.Method != "Total") %>%
#     filter(Appt.YearQtr %in% tail(data_quarters,5)) %>%
#     mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
#     group_by(Campus.Specialty.SubGroup, Appt.YearQtr, Appt.Month, Visit.Method) %>%
#     summarise(monthly_vol = sum(monthly_vol)) %>%
#     mutate(perc = percent(monthly_vol/sum(monthly_vol),0))
#   
#   
#   monthOptions <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
#   
#   ggplot(dept_vol, aes(x= factor(Appt.Month, levels = monthOptions),
#                        y=monthly_vol, group=Visit.Method, fill=Visit.Method))+
#     geom_bar(position="stack",stat="identity", width=0.7)+
#     facet_grid(.~Appt.YearQtr, scales = "free", space = "free_x") + 
#     scale_fill_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000","#7030a0","#5753d0","#5cd3ff"))+
#     scale_y_continuous(limits=c(0, max((dept_vol %>% group_by(Appt.YearQtr, Appt.Month) %>% summarise(total = sum(monthly_vol)))$total)*1.1), 
#                        labels = scales::number_format(accuracy = 1),
#                        expand = c(0,0))+
#     labs(title = "Ambulatory Visit Volume",
#          subtitle = department,
#          x = NULL, y = NULL, fill = "Site")+
#     theme_bw()+
#     theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="8"),
#             legend.direction = "horizontal",
#             legend.title = element_blank(),
#             axis.title = element_blank(),
#             axis.text = element_text(size="10"),
#             axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     geom_text(aes(label=paste0(prettyNum(monthly_vol, big.mark = ','),"\n","(",perc,")")), color="white", 
#                 size=2.5, fontface="bold", position = position_stack(vjust = 0.5))+
#     stat_summary(fun.y = sum, vjust = -1, aes(label=ifelse(..y.. == 0,"",prettyNum(..y.., big.mark = ',')), group = Appt.Month), geom="text", color="black", 
#                  size=3.5)+
#     guides(fill = guide_legend(nrow = 1))
#     
# }

```


```{r Monthly Volume Site Breakout Output, echo = FALSE, warning = FALSE, message = FALSE}

theme_new_line <- function(base_size = 12,
                           base_family = "Calibri",
                           base_line_size = base_size / 170,
                           base_rect_size = base_size / 170) {
  theme_bw(
    base_size = base_size,
    base_family = base_family,
    base_line_size = base_line_size
  ) %+replace%
    theme(plot.title = element_text(hjust=0.5, face = "bold", size = 20),
          plot.subtitle = element_text(hjust=0.5,vjust=-1, size = 16, face = "italic"),
          plot.caption = element_text(hjust = 0, size = 14, face = "italic"),
          legend.position = "top",
          legend.text = element_text(size="12"),
          legend.direction = "horizontal",
          legend.key.size = unit(1.0,"cm"),
          legend.title = element_blank(),
          axis.title = element_text(size="14"),
          axis.text = element_text(size="12"),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(size = 0.3, colour = "black"),
          plot.margin = margin(10,10,10,10))
}

deptSite_monthly_vol_function_1 <- function(department){
  
  # department <- i
  
  monthOptions <- c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")

vol_trending <- monthly_vol %>%
  filter(Specialty == department) %>%
  filter(Visit.Method == "Total") %>%
  mutate(Appt.Year = format(Appt.YearQtr, "%Y")) %>%
  filter(Appt.Year %in% c(reporting_year, as.character(as.numeric(reporting_year)-1))) %>%
  group_by(Campus, Appt.Year, Appt.Month) %>%
  summarise(monthly_vol = sum(monthly_vol)) %>%
  pivot_wider(names_from = Appt.Year,
              values_from = monthly_vol) %>%
  arrange(factor(Appt.Month, levels = monthOptions)) %>%
  arrange(Campus)

vol_trending$perc_change <- round((vol_trending$`2022` - vol_trending$`2021`)/vol_trending$`2021`,2)*100
vol_trending <- vol_trending %>%
  pivot_longer(3:5,
               names_to = "variable",
               values_to = "value") %>%
  mutate(status = ifelse(variable == "perc_change","% Variance","Total Visits"))

vol_trending$value[which(vol_trending$variable == "perc_change" & is.na(vol_trending$value))] <- 0
vol_trending$Appt.Month <- factor(vol_trending$Appt.Month, levels=monthOptions)
vol_trending$status <- factor(vol_trending$status, levels=c("Total Visits","% Variance"))
# vol_trending <- vol_trending %>% filter(Campus %in% c("MSBI","MSH- AMBULATORY CARE","MSH-MSDFP","MSM","MSUS","MSW"))
# 
# ggplot(vol_trending, aes_string(x = "Appt.Month", y = "value")) +  
#   facet_grid(status~Campus, scales="free_y", switch = "y") + 
#   geom_line(data = subset(vol_trending, status == "Total Visits"), aes(color = variable, group = variable), na.rm = TRUE, show_guide = TRUE)+
#   geom_point(data = subset(vol_trending, status == "Total Visits"), aes(color = variable, group = variable), size = 2, na.rm = TRUE, show_guide = TRUE)+
#   # geom_col(data = subset(vol_trending, status == "bar"), aes(fill = ifelse(value > 0, "#ff3300", "#00b800")),  show_guide = TRUE)+
#   geom_bar(data = subset(vol_trending, status == "% Variance"), aes(fill=(value>0)), na.rm = TRUE, show_guide = FALSE, show.legend = FALSE, stat="identity")+
#   scale_fill_manual(values = c('#ff3300', '#00b800'))+
#   scale_color_manual(name = NULL, values =  c("#212070","#d80b8c"))+
#   # geom_text(data = subset(vol_trending, status == "Total Visits"), aes(label=prettyNum(value,',')), color="black",
#   #           fontface="bold",hjust=-.25, nudge_y = 2, nudge_x = -.1, size=3)+
#   geom_text(data = subset(vol_trending, status == "% Variance"), aes(label=paste0(value,"%")), color="black", 
#                 size=3, fontface="bold", position = position_stack(vjust = .5))+
#   force_panelsizes(rows = c(1, 0.6))+
#   theme_bw()+
#   theme(strip.text.y = element_text(size = 10, color = "black", face = "bold"),
#         strip.text.x = element_text(size = 10, color = "black", face = "bold"),
#         strip.background = element_rect(fill=NA),
#         legend.position = "top")+
#   labs(x = "Month", y = "")+
#   guides(fill=FALSE) 
       
       
campuses <- sort(unique(vol_trending$Campus))

data1 <- vol_trending %>% filter(Campus %in% campuses[1:(length(campuses)/2)-1])

ggplot(data1, aes_string(x = "Appt.Month", y = "value")) +
  facet_grid(status~Campus, scales="free_y", switch = "y") +
  geom_line(data = subset(data1, status == "Total Visits"), aes(color = variable, group = variable), na.rm = TRUE, show_guide = TRUE)+
  geom_point(data = subset(data1, status == "Total Visits"), aes(color = variable, group = variable), size = 2, na.rm = TRUE, show_guide = TRUE)+
  # geom_col(data = subset(data1, status == "bar"), aes(fill = ifelse(value > 0, "#ff3300", "#00b800")),  show_guide = TRUE)+
  geom_bar(data = subset(data1, status == "% Variance"), aes(fill=(value>0)), na.rm = TRUE, show_guide = FALSE, show.legend = FALSE, stat="identity")+
  scale_fill_manual(values = c('#ff9980', '#99e699'))+
  scale_color_manual(name = NULL, values =  c("#212070","#d80b8c"))+
  # geom_text(data = subset(data1, status == "Total Visits"), aes(label=prettyNum(value,',')), color="black",
  #           fontface="bold",hjust=-.25, nudge_y = 2, nudge_x = -.1, size=3)+
  geom_text(data = subset(data1, status == "% Variance"), aes(label=paste0(value,"%")), color="black",
                size=3, fontface="bold", position = position_stack(vjust = .5))+
  force_panelsizes(rows = c(1, 0.6))+
  theme_bw()+
  theme(strip.text.y = element_text(size = 10, color = "black", face = "bold"),
        strip.text.x = element_text(size = 10, color = "black", face = "bold"),
        strip.background = element_rect(fill="#e5e6e5"),
        legend.position = "top")+
  labs(x = "", y = "")+
  guides(fill=FALSE,color=FALSE)


}


deptSite_monthly_vol_function_2 <- function(department){
  # 
  # department <- "Anesthesiology/Pain Management"
  
  monthOptions <- c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")

vol_trending <- monthly_vol %>%
  filter(Specialty == department) %>%
  filter(Visit.Method == "Total") %>%
  mutate(Appt.Year = format(Appt.YearQtr, "%Y")) %>%
  filter(Appt.Year %in% c(reporting_year, as.character(as.numeric(reporting_year)-1))) %>%
  group_by(Campus, Appt.Year, Appt.Month) %>%
  summarise(monthly_vol = sum(monthly_vol)) %>%
  pivot_wider(names_from = Appt.Year,
              values_from = monthly_vol) %>%
  arrange(factor(Appt.Month, levels = monthOptions)) %>%
  arrange(Campus)

vol_trending$perc_change <- round((vol_trending$`2022` - vol_trending$`2021`)/vol_trending$`2021`,2)*100
vol_trending <- vol_trending %>%
  pivot_longer(3:5,
               names_to = "variable",
               values_to = "value") %>%
  mutate(status = ifelse(variable == "perc_change","% Variance","Total Visits"))


vol_trending$value[which(vol_trending$variable == "perc_change" & is.na(vol_trending$value))] <- 0
vol_trending$Appt.Month <- factor(vol_trending$Appt.Month, levels=monthOptions)
vol_trending$status <- factor(vol_trending$status, levels=c("Total Visits","% Variance"))

campuses <- sort(unique(vol_trending$Campus))

data2 <- vol_trending %>% filter(Campus %in% campuses[(length(campuses)/2+1):length(campuses)])

ggplot(data2, aes_string(x = "Appt.Month", y = "value")) +
  facet_grid(status~Campus, scales="free_y", switch = "y") +
  geom_line(data = subset(data2, status == "Total Visits"), aes(color = variable, group = variable), na.rm = TRUE, show_guide = TRUE)+
  geom_point(data = subset(data2, status == "Total Visits"), aes(color = variable, group = variable), size = 2, na.rm = TRUE, show_guide = TRUE)+
  # geom_col(data = subset(data2, status == "bar"), aes(fill = ifelse(value > 0, "#ff3300", "#00b800")),  show_guide = TRUE)+
  geom_bar(data = subset(data2, status == "% Variance"), aes(fill=(value>0)), na.rm = TRUE, show_guide = FALSE, show.legend = FALSE, stat="identity")+
  scale_fill_manual(values = c('#ff9980', '#99e699'))+
  scale_color_manual(name = NULL, values =  c("#212070","#d80b8c"))+
  # geom_text(data = subset(data2, status == "Total Visits"), aes(label=prettyNum(value,',')), color="black",
  #           fontface="bold",hjust=-.25, nudge_y = 2, nudge_x = -.1, size=3)+
  geom_text(data = subset(data2, status == "% Variance"), aes(label=paste0(value,"%")), color="black",
                size=3, fontface="bold", position = position_stack(vjust = .5))+
  force_panelsizes(rows = c(1, 0.6))+
  theme_bw()+
  theme(strip.text.y = element_text(size = 10, color = "black", face = "bold"),
        strip.text.x = element_text(size = 10, color = "black", face = "bold"),
        strip.background = element_rect(fill="#e5e6e5"),
        legend.position = "top")+
  labs(x = "", y = "")+
  guides(fill=FALSE, color=FALSE)

}


deptSite_monthly_vol_function <- function(department){
  # 
  # department <- "Anesthesiology/Pain Management"
  # department <- i
  
  monthOptions <- c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")

vol_trending <- monthly_vol %>%
  filter(Specialty == department) %>%
  filter(Visit.Method == "Total") %>%
  mutate(Appt.Year = format(Appt.YearQtr, "%Y")) %>%
  filter(Appt.Year %in% c(reporting_year, as.character(as.numeric(reporting_year)-1))) %>%
  group_by(Campus, Appt.Year, Appt.Month) %>%
  summarise(monthly_vol = sum(monthly_vol)) %>%
  pivot_wider(names_from = Appt.Year,
              values_from = monthly_vol) %>%
  arrange(factor(Appt.Month, levels = monthOptions)) %>%
  arrange(Campus)

vol_trending$perc_change <- round((vol_trending$`2022` - vol_trending$`2021`)/vol_trending$`2021`,2)*100
vol_trending <- vol_trending %>%
  pivot_longer(3:5,
               names_to = "variable",
               values_to = "value") %>%
  mutate(status = ifelse(variable == "perc_change","% Variance","Total Visits"))


vol_trending$value[which(vol_trending$variable == "perc_change" & is.na(vol_trending$value))] <- 0
vol_trending$Appt.Month <- factor(vol_trending$Appt.Month, levels=monthOptions)
vol_trending$status <- factor(vol_trending$status, levels=c("Total Visits","% Variance"))

campuses <- sort(unique(vol_trending$Campus))

data <- vol_trending

ggplot(data, aes_string(x = "Appt.Month", y = "value")) +
  facet_grid(status~Campus, scales="free_y", switch = "y") +
  geom_line(data = subset(data, status == "Total Visits"), aes(color = variable, group = variable), na.rm = TRUE, show_guide = TRUE)+
  geom_point(data = subset(data, status == "Total Visits"), aes(color = variable, group = variable), size = 2, na.rm = TRUE, show_guide = TRUE)+
  # geom_col(data = subset(data2, status == "bar"), aes(fill = ifelse(value > 0, "#ff3300", "#00b800")),  show_guide = TRUE)+
  geom_bar(data = subset(data, status == "% Variance"), aes(fill=(value>0)), na.rm = TRUE, show_guide = FALSE, show.legend = FALSE, stat="identity")+
  scale_fill_manual(values = c('#ff9980', '#99e699'))+
  scale_color_manual(name = NULL, values =  c("#212070","#d80b8c"))+
  # geom_text(data = subset(data2, status == "Total Visits"), aes(label=prettyNum(value,',')), color="black",
  #           fontface="bold",hjust=-.25, nudge_y = 2, nudge_x = -.1, size=3)+
  geom_text(data = subset(data, status == "% Variance"), aes(label=paste0(value,"%")), color="black",
                size=3, fontface="bold", position = position_stack(vjust = .5))+
  force_panelsizes(rows = c(1, 0.6))+
  theme_bw()+
  theme(strip.text.y = element_text(size = 10, color = "black", face = "bold"),
        strip.text.x = element_text(size = 10, color = "black", face = "bold"),
        strip.background = element_rect(fill="#e5e6e5"),
        legend.position = "top")+
  labs(x = "", y = "")+
  guides(fill=FALSE, color=FALSE)

}
```


```{r Monthly Volume Graph Key Takeaways, echo = FALSE, warning = FALSE, message = FALSE}

dept_monthly_vol_takeaway <- function(department){
  
  qrt_vol_var <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Visit.Method == "Total") %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)],
                                 data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Appt.YearQtr) %>%
    summarise(total = sum(monthly_vol)) %>%
    pivot_wider(names_from = Appt.YearQtr,
                values_from = total) %>%
    mutate(var_last_qrt = percent((.[[3]]/.[[2]])-1,1),
           var_last_yr = percent((.[[3]]/.[[1]])-1,1))
  
  qrt_vol <- as.character(prettyNum(qrt_vol_var[[3]], big.mark = ','))
  var_last_qrt <- as.character(ifelse(qrt_vol_var[[4]] > 0, paste0("+",qrt_vol_var[[4]]),as.character(qrt_vol_var[[4]])))
  var_last_yr <- as.character(ifelse(qrt_vol_var[[5]] > 0, paste0("+",qrt_vol_var[[5]]), as.character(qrt_vol_var[[5]])))
  
  # MSHS Overall
  mshs_qrt_vol_var <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    # filter(Specialty == department) %>%
    filter(Visit.Method == "Total") %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)],
                                 data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Appt.YearQtr) %>%
    summarise(total = sum(monthly_vol)) %>%
    pivot_wider(names_from = Appt.YearQtr,
                values_from = total) %>%
    mutate(var_last_qrt = percent((.[[3]]/.[[2]])-1,1),
           var_last_yr = percent((.[[3]]/.[[1]])-1,1))
  
  mshs_qrt_vol <- as.character(prettyNum(mshs_qrt_vol_var[[3]], big.mark = ','))
  mshs_var_last_qrt <- as.character(ifelse(mshs_qrt_vol_var[[4]] > 0, paste0("+",mshs_qrt_vol_var[[4]]),as.character(mshs_qrt_vol_var[[4]])))
  mshs_var_last_yr <- as.character(ifelse(mshs_qrt_vol_var[[5]] > 0, paste0("+",mshs_qrt_vol_var[[5]]), as.character(mshs_qrt_vol_var[[5]])))
  
  # Median % Change across all departments
  dept_qrt_vol_var <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    # filter(Specialty == department) %>%
    filter(Visit.Method == "Total") %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)],
                                 data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Appt.YearQtr, Specialty) %>%
    summarise(total = sum(monthly_vol)) %>%
    pivot_wider(names_from = Appt.YearQtr,
                values_from = total) %>%
    filter(!is.na(.[[4]])) %>%
    mutate(var_last_qrt = percent((.[[4]]/.[[3]])-1,1),
           var_last_yr = percent((.[[4]]/.[[2]])-1,1))
  
  dept_var_last_qrt <- as.character(ifelse(median(dept_qrt_vol_var[[5]]) > 0,
                                           paste0("+",median(dept_qrt_vol_var[[5]])),as.character(median(dept_qrt_vol_var[[5]]))))
  dept_var_last_yr <- as.character(ifelse(median(dept_qrt_vol_var[[6]]) > 0, 
                                          paste0("+",median(dept_qrt_vol_var[[6]])), as.character(median(dept_qrt_vol_var[[6]]))))
  
  avg_monthly <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Visit.Method == "Total") %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
    group_by(Campus.Specialty.Group, Appt.Month) %>%
    summarise(total = sum(monthly_vol)) 
  
  avg_month <- as.character(prettyNum(round(mean(avg_monthly$total)), big.mark = ','))
  
  visit_method_vol <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
    filter(Visit.Method != "Total") %>%
    group_by(Specialty, Visit.Method) %>%
    summarise(total = sum(monthly_vol)) %>%
    ungroup() %>%
    group_by(Specialty) %>%
    mutate(perc = percent(total/sum(total),0))
  
  in_person <- as.character(visit_method_vol$perc[which(visit_method_vol$Visit.Method == "IN PERSON")])
  
  site_vol <- monthly_vol %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Visit.Method == "Total") %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Specialty, Appt.YearQtr, Campus) %>%
    summarise(monthly_vol = sum(monthly_vol)) %>%
    group_by(Specialty, Appt.YearQtr) %>%
    mutate(perc = percent(monthly_vol/sum(monthly_vol),0)) %>%
    filter(perc == max(perc))
  
  max_vol <- as.character(prettyNum(site_vol$monthly_vol, big.mark = ','))
  max_vol_perc <- as.character(site_vol$perc, big.mark = ',')
  max_site <- as.character(site_vol$Campus)
  
  key_list <- list(in_person, qrt_vol, avg_month, var_last_qrt, var_last_yr, max_site, max_vol, max_vol_perc, 
                   mshs_var_last_qrt,  mshs_var_last_yr,
                   dept_var_last_qrt, dept_var_last_yr)
  
  return(key_list)
}


# dept_monthly_vol_takeaway_sub <- function(department){
#   
#   qrt_vol_var <- monthly_vol %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Visit.Method == "Total") %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)], data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
#     mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
#     group_by(Appt.YearQtr) %>%
#     summarise(total = sum(monthly_vol)) %>%
#     pivot_wider(names_from = Appt.YearQtr,
#                 values_from = total) %>%
#     mutate(var_last_qrt = percent((.[[1]]/.[[2]])-1,0),
#            var_last_yr = percent((.[[1]]/.[[3]])-1,0))
#   
#   qrt_vol <- as.character(prettyNum(qrt_vol_var[[1]], big.mark = ','))
#   var_last_qrt <- as.character(qrt_vol_var[[4]])
#   var_last_yr <- as.character(qrt_vol_var[[5]])
#   
#   avg_monthly <- monthly_vol %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Visit.Method == "Total") %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
#     group_by(Campus.Specialty.SubGroup, Appt.Month) %>%
#     summarise(total = sum(monthly_vol)) 
#   
#   avg_month <- as.character(prettyNum(round(mean(avg_monthly$total)), big.mark = ','))
#   
#   visit_method_vol <- monthly_vol %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
#     filter(Visit.Method != "Total") %>%
#     group_by(Campus.Specialty.SubGroup, Visit.Method) %>%
#     summarise(total = sum(monthly_vol)) %>%
#     ungroup() %>%
#     group_by(Campus.Specialty.SubGroup) %>%
#     mutate(perc = percent(total/sum(total),0))
#   
#   in_person <- as.character(visit_method_vol$perc[which(visit_method_vol$Visit.Method == "IN PERSON")])
#   
#   site_vol <- monthly_vol %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Visit.Method == "Total") %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) %>%
#     mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
#     group_by(Campus.Specialty.SubGroup, Appt.YearQtr, Campus) %>%
#     summarise(monthly_vol = sum(monthly_vol)) %>%
#     group_by(Campus.Specialty.SubGroup, Appt.YearQtr) %>%
#     mutate(perc = percent(monthly_vol/sum(monthly_vol),0)) %>%
#     filter(perc == max(perc))
#   
#   max_vol <- as.character(prettyNum(site_vol$monthly_vol, big.mark = ','))
#   max_vol_perc <- as.character(site_vol$perc, big.mark = ',')
#   max_site <- as.character(site_vol$Campus)
#   
#   key_list <- list(in_person, qrt_vol, avg_month, var_last_qrt, var_last_yr, max_site, max_vol, max_vol_perc)
#   
#   return(key_list)
# }

```


```{r Monthly Volume Heat Map Graph Output, echo = FALSE, warning = FALSE, message = FALSE}

dept_heat_map_function <- function(department){
  # department <- "Medicine - Infectious Diseases/Travel Medicine"
  # department <- i
  dept_vol_zip_code <- vol_zip_code %>%
    filter(Specialty == department) %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) 
  
  # Create a color palette with handmade bins.
      mybins <- round(seq(0 , round_any(max(dept_vol_zip_code$total_vol), as.numeric(str_count(max(dept_vol_zip_code$total_vol))), f = ceiling) , length.out=5),0)
      mypalette <- colorBin(palette=MountSinai_palettes$pinkBlue, domain=quakes$mag, na.color="transparent", bins=mybins)
      
      # Prepare the text for the tooltip:
      mytext <- paste(
        "Total Visit Volume: ", dept_vol_zip_code$total_vol, "<br/>") %>%
        lapply(htmltools::HTML)
      
      icons <- awesomeIcons(
      icon = 'hospital-o',
      lib = 'fa',
      iconColor = "white",
      markerColor = "lightgray")
      
      map <-
        leaflet(data = dept_vol_zip_code) %>%
        addProviderTiles("CartoDB.Positron", options = providerTileOptions(noWrap = TRUE)) %>%
        setView(lng=-73.99181, lat=40.76719, zoom = 12) %>%
        addCircleMarkers(lng = ~lng, lat = ~lat, 
                         fillColor = ~mypalette(total_vol), fillOpacity = 0.9, color="white", stroke=FALSE,
                         # color = ~groupColors(SITE),
                         # group = ~SITE, 
                         radius= 21,
                         # label = mytext,
                         # labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "18px", direction = "auto")
                         ) %>%
        addLabelOnlyMarkers(~lng, ~lat, label =  ~prettyNum(total_vol, big.mark = ','), 
                      labelOptions = labelOptions(noHide = T, direction = 'center', textOnly = T, textsize = "22px",
                                                  style = list("font-weight" = "bold", padding = "3px 8px"))) %>%
        leaflet::addLegend(pal=mypalette, values=~total_vol, opacity=0.9, title = "Total Visit Volume", position = "topright")
      
      
      map <- map %>%
      addAwesomeMarkers(
        lng=-73.943324, lat=40.79171,
        # label='MSH',
        label=NULL,
        icon = icons,
        labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
                                    style=list('font-weight'= 'bold'))) %>%
      addAwesomeMarkers(
        lng=-73.92606, lat=40.77084,
        # label='MSQ',
        label=NULL,
        icon = icons,
        labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
                                    style=list('font-weight'= 'bold'))) %>%
      addAwesomeMarkers(
        lng=-73.98840, lat=40.73139,
        # label='MSUS',
        label=NULL,
        icon = icons,
        labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
                                    style=list('font-weight'= 'bold'))) %>%
      addAwesomeMarkers(
        lng=-73.99181, lat=40.76719,
        # label='MSW',
        label=NULL,
        icon = icons,
        labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
                                    style=list('font-weight'= 'bold'))) %>%
      addAwesomeMarkers(
        lng=-73.96316, lat=40.79834,
        # label="MSM",
        label=NULL,
        icon = icons,
        labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
                                    style=list('font-weight'= 'bold')))
       
      
      # Save as a png
      saveWidget(map, "vol_heat_map.html", selfcontained = FALSE)
      webshot("vol_heat_map.html", file = "vol_heat_map.png", cliprect = "viewport")
               # c(0, 200, 1000, 1400)
      
      # vol_heat_map_graph <- readPNG("vol_heat_map.png")
      # 
      # return(vol_heat_map_graph)
}


# dept_heat_map_function_sub <- function(department){
#   
#   # department <- i
#   dept_vol_zip_code <- vol_zip_code %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)])) 
#   
#   # Create a color palette with handmade bins.
#       mybins <- round(seq(0 , round_any(max(dept_vol_zip_code$total_vol), as.numeric(str_count(max(dept_vol_zip_code$total_vol))), f = ceiling) , length.out=5),0)
#       mypalette <- colorBin(palette=MountSinai_palettes$pinkBlue, domain=quakes$mag, na.color="transparent", bins=mybins)
#       
#       # Prepare the text for the tooltip:
#       mytext <- paste(
#         "Total Visit Volume: ", dept_vol_zip_code$total_vol, "<br/>") %>%
#         lapply(htmltools::HTML)
#       
#       icons <- awesomeIcons(
#       icon = 'hospital-o',
#       lib = 'fa',
#       iconColor = "white",
#       markerColor = "lightgray")
#       
#       map <-
#         leaflet(data = dept_vol_zip_code) %>%
#         addProviderTiles("CartoDB.Positron", options = providerTileOptions(noWrap = TRUE)) %>%
#         setView(lng=-73.99181, lat=40.76719, zoom = 12) %>%
#         addCircleMarkers(lng = ~lng, lat = ~lat, 
#                          fillColor = ~mypalette(total_vol), fillOpacity = 0.9, color="white", stroke=FALSE,
#                          # color = ~groupColors(SITE),
#                          # group = ~SITE, 
#                          radius= 21,
#                          # label = mytext,
#                          # labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "18px", direction = "auto")
#                          ) %>%
#         addLabelOnlyMarkers(~lng, ~lat, label =  ~prettyNum(total_vol, big.mark = ','), 
#                       labelOptions = labelOptions(noHide = T, direction = 'center', textOnly = T, textsize = "22px",
#                                                   style = list("font-weight" = "bold", padding = "3px 8px"))) %>%
#         leaflet::addLegend(pal=mypalette, values=~total_vol, opacity=0.9, title = "Total Visit Volume", position = "topright")
#       
#       
#       map <- map %>%
#       addAwesomeMarkers(
#         lng=-73.943324, lat=40.79171,
#         # label='MSH',
#         label=NULL,
#         icon = icons,
#         labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
#                                     style=list('font-weight'= 'bold'))) %>%
#       addAwesomeMarkers(
#         lng=-73.92606, lat=40.77084,
#         # label='MSQ',
#         label=NULL,
#         icon = icons,
#         labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
#                                     style=list('font-weight'= 'bold'))) %>%
#       addAwesomeMarkers(
#         lng=-73.98840, lat=40.73139,
#         # label='MSUS',
#         label=NULL,
#         icon = icons,
#         labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
#                                     style=list('font-weight'= 'bold'))) %>%
#       addAwesomeMarkers(
#         lng=-73.99181, lat=40.76719,
#         # label='MSW',
#         label=NULL,
#         icon = icons,
#         labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
#                                     style=list('font-weight'= 'bold'))) %>%
#       addAwesomeMarkers(
#         lng=-73.96316, lat=40.79834,
#         # label="MSM",
#         label=NULL,
#         icon = icons,
#         labelOptions = labelOptions(noHide = T, textsize='14px', textOnly = TRUE, direction = 'right',
#                                     style=list('font-weight'= 'bold')))
#        
#       
#       # Save as a png
#       saveWidget(map, "vol_heat_map.html", selfcontained = FALSE)
#       webshot("vol_heat_map.html", file = "vol_heat_map.png", cliprect = "viewport")
#                # c(0, 200, 1000, 1400)
#       
#       # vol_heat_map_graph <- readPNG("vol_heat_map.png")
#       # 
#       # return(vol_heat_map_graph)
# }

```


```{r Time to Appointment Distribution Table Output, echo = FALSE, warning = FALSE, message = FALSE}

overall_time_to_appt_dist_function <- function(department){
  
  wait_time <- waitTime_dist_specialty %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0))
  
  graph <- ggplot(wait_time, aes(x=factor(group, levels=c(">30","15-30","8-14","0-7")), y=perc, fill = New.PT2)) +
    geom_col(width = 0.8)+
    scale_y_continuous(limits=c(0, 1.1),
                       labels = scales::percent_format(accuracy = 1),
                       expand = c(0,0))+
    coord_flip()+
    facet_grid(New.PT2 ~ Visit.Method, scales = "free_y", switch = "y")+
    scale_fill_manual(values=c("#212070","#d80b8c"))+
    labs(title = "Time to Appointment Horizon",
         subtitle = department,
         x = NULL, y = "% of Total Appointments Scheduled", fill = NULL)+
    theme_bw()+
    theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
            plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
            legend.position = "bottom",
            legend.text = element_text(size="8"),
            legend.direction = "horizontal",
            legend.title = element_blank(),
            axis.title = element_text(size="8"),
            axis.text = element_text(size="8"),
            # axis.title.x = element_blank(),
            axis.line = element_line(size = 0.3, colour = "black"))+
    geom_text(aes(label= paste0(perc, " (", prettyNum(total, big.mark = ','),")")), hjust = -.1, vjust=.5, color="black", size=3, font.face = "bold")
  
  return(graph)
  
}


# overall_time_to_appt_dist_function_sub <- function(department){
#   
#   wait_time <- waitTime_dist_specialty %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
#     group_by(New.PT2, Visit.Method) %>%
#     mutate(perc = formattable::percent(total/sum(total),0))
#   
#   graph <- ggplot(wait_time, aes(x=factor(group, levels=c(">30","15-30","8-14","0-7")), y=perc, fill = New.PT2)) +
#     geom_col(width = 0.8)+
#     scale_y_continuous(limits=c(0, 1.1),
#                        labels = scales::percent_format(accuracy = 1),
#                        expand = c(0,0))+
#     coord_flip()+
#     facet_grid(New.PT2 ~ Visit.Method, scales = "free_y", switch = "y")+
#     scale_fill_manual(values=c("#212070","#d80b8c"))+
#     labs(title = "Time to Appointment Horizon",
#          subtitle = department,
#          x = NULL, y = "% of Total Appointments Scheduled", fill = NULL)+
#     theme_bw()+
#     theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="8"),
#             legend.direction = "horizontal",
#             legend.title = element_blank(),
#             axis.title = element_text(size="8"),
#             axis.text = element_text(size="8"),
#             # axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     geom_text(aes(label= paste0(perc, " (", prettyNum(total, big.mark = ','),")")), hjust = -.1, vjust=.5, color="black", size=3, font.face = "bold")
#   
#   return(graph)
#   
# }

```


```{r Time to Appointment Table Output, echo = FALSE, warning = FALSE, message = FALSE}

site_time_to_appt_function <- function(department){
  
  wait_time <- waitTime_site %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    mutate(med_wait = round(as.numeric(med_wait))) %>%
    pivot_wider(names_from = New.PT2,
                values_from = med_wait,
                values_fill = 0) %>%
    pivot_longer(6:7,
                 names_to = "New.PT2",
                 values_to = "med_wait")
  
  graph <- ggplot(wait_time, aes(x=reorder(Campus, med_wait), y=med_wait, group = New.PT2, fill = New.PT2)) +
    geom_col(width = 0.8)+
    geom_hline(yintercept = 14, linetype="dashed", color = "red", size = 1)+
    coord_flip()+
    facet_grid(. ~ New.PT2)+
    scale_y_continuous(limits=c(0, max(wait_time$med_wait)*1.1), 
                       # labels = scales::number_format(accuracy = 1),
                       expand = c(0,0))+
    scale_fill_manual(values=c("#212070","#d80b8c"))+
    labs(title = "Time to Appointment (Median Days) by Site",
         subtitle = department,
         x = NULL, y = "Median Days", fill = "Site",
         caption = "*Target: 14 days")+
    theme_bw()+
    theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
          plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
          plot.caption = element_text(size = 8, face = "bold.italic", color = "red"),
            legend.position = "bottom",
            legend.text = element_text(size="8"),
            legend.direction = "horizontal",
            legend.title = element_blank(),
            axis.title = element_text(size="8"),
            axis.text = element_text(size="8"),
            # axis.title.x = element_blank(),
            axis.line = element_line(size = 0.3, colour = "black"))+
    geom_text(aes(label= ifelse(med_wait == 0, "", med_wait)), hjust = -.1, vjust=.5, color="black", size=3, font.face = "bold")
  
  return(graph)
    
}


# site_time_to_appt_function_sub <- function(department){
#   
#   wait_time <- waitTime_site %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
#     mutate(med_wait = as.numeric(med_wait)) %>%
#     pivot_wider(names_from = New.PT2,
#                 values_from = med_wait,
#                 values_fill = 0) %>%
#     pivot_longer(5:6,
#                  names_to = "New.PT2",
#                  values_to = "med_wait")
#   
#   graph <- ggplot(wait_time, aes(x=reorder(Campus, med_wait), y=med_wait, group = New.PT2, fill = New.PT2)) +
#     geom_col(width = 0.8)+
#     geom_hline(yintercept = 14, linetype="dashed", color = "red", size = 1)+
#     coord_flip()+
#     facet_grid(. ~ New.PT2)+
#     scale_y_continuous(limits=c(0, max(wait_time$med_wait)*1.1), 
#                        # labels = scales::number_format(accuracy = 1),
#                        expand = c(0,0))+
#     scale_fill_manual(values=c("#212070","#d80b8c"))+
#     labs(title = "Time to Appointment by Site",
#          subtitle = department,
#          x = NULL, y = "Median Days", fill = "Site",
#          caption = "*Target: 14 days")+
#     theme_bw()+
#     theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#           plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#           plot.caption = element_text(size = 8, face = "bold.italic", color = "red"),
#             legend.position = "bottom",
#             legend.text = element_text(size="8"),
#             legend.direction = "horizontal",
#             legend.title = element_blank(),
#             axis.title = element_text(size="8"),
#             axis.text = element_text(size="8"),
#             # axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     geom_text(aes(label= ifelse(med_wait == 0, "", med_wait)), hjust = -.1, vjust=.5, color="black", size=3, font.face = "bold")
#   
#   return(graph)
#     
# }

```


```{r Access Graph Key Takeaways, echo = FALSE, warning = FALSE, message = FALSE}

dept_access_takeaway <- function(department){
  
  # Department
  wait_time_new <- waitTime_dist_specialty %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0))
  
  new_pt_vol <- as.character(prettyNum(sum((wait_time_new %>% filter(New.PT2 == "New"))$total), big.mark = ','))
  new_pt_vol_perc <- as.character(percent((sum((wait_time_new %>% filter(New.PT2 == "New"))$total) / sum((wait_time_new$total))),0))
  new_inPerson_14days <- as.character(sum((wait_time_new %>% filter(New.PT2 == "New" & Visit.Method == "IN PERSON" & group %in% c("0-7","8-14")))$perc))
  new_tele_14days <- as.character(sum((wait_time_new %>% filter(New.PT2 == "New" & Visit.Method == "TELEHEALTH" & group %in% c("0-7","8-14")))$perc))
  
  dept_med_waitTime <- as.character(unique(as.numeric((wait_time_new %>% filter(New.PT2 == "New"))$med_wait)))
  
  
  # MSHS
  mshs_wait_time_new <- waitTime_dist_specialty %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(New.PT2) %>%
    summarise(total = sum(total)) %>%
    mutate(new_perc = total/sum(total))
  
  mshs_new_pt_vol_perc <- as.character(percent(mshs_wait_time_new$new_perc[which(mshs_wait_time_new$New.PT2 == "New")],0))
  

  mshs_new_pt_14days <- waitTime_dist_specialty %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(New.PT2, Visit.Method, group) %>%
    summarise(total = sum(total)) %>%
    group_by(New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0)) 
    
  mshs_new_inPerson_14days <- as.character(sum((mshs_new_pt_14days %>%
                                                  filter(New.PT2 == "New" & Visit.Method == "IN PERSON" & group %in% c("0-7","8-14")))$perc))
  
  mshs_new_tele_14days <- as.character(sum((mshs_new_pt_14days %>%
                                                  filter(New.PT2 == "New" & Visit.Method == "TELEHEALTH" & group %in% c("0-7","8-14")))$perc))
  
  
  # Across Departments
  specialty_wait_time_new <- waitTime_dist_specialty %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0))
  
  specialty_new_pt_vol <- specialty_wait_time_new %>%
    group_by(Specialty, New.PT2) %>%
    summarise(total = sum(total)) %>%
    group_by(Specialty) %>%
    mutate(new_perc = total/sum(total)) %>%
    filter(New.PT2 == "New")
  specialty_new_pt_vol_perc <- as.character(median(percent(specialty_new_pt_vol$new_perc,0)))
  

  specialty_new_pt_14days <- waitTime_dist_specialty %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(Specialty, New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0)) %>%
    filter(New.PT2 == "New" & Visit.Method == "IN PERSON" & group %in% c("0-7","8-14")) %>%
   group_by(Specialty, New.PT2, Visit.Method) %>%
    summarise(perc = sum(perc))
  specialty_new_inPerson_14days <- as.character(median(specialty_new_pt_14days$perc))
  
  specialty_new_pt_14days <- waitTime_dist_specialty %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    group_by(Specialty, New.PT2, Visit.Method) %>%
    mutate(perc = formattable::percent(total/sum(total),0)) %>%
    filter(New.PT2 == "New" & Visit.Method == "TELEHEALTH" & group %in% c("0-7","8-14")) %>%
   group_by(Specialty, New.PT2, Visit.Method) %>%
    summarise(perc = sum(perc))
  specialty_new_tele_14days <- as.character(median(specialty_new_pt_14days$perc))
  
  
  
  key_list <- list(new_pt_vol, new_pt_vol_perc, new_inPerson_14days, new_tele_14days, dept_med_waitTime,
                   mshs_new_pt_vol_perc, mshs_new_inPerson_14days,  mshs_new_tele_14days,
                   specialty_new_pt_vol_perc, specialty_new_inPerson_14days, specialty_new_tele_14days)
  
  return(key_list)
}


# dept_access_takeaway_sub <- function(department){
#   
#   wait_time_new <- waitTime_dist_specialty %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
#     group_by(New.PT2, Visit.Method) %>%
#     mutate(perc = formattable::percent(total/sum(total),0))
#   
#   new_pt_vol <- as.character(prettyNum(sum((wait_time_new %>% filter(New.PT2 == "New"))$total), big.mark = ','))
#   new_pt_vol_perc <- as.character(percent((sum((wait_time_new %>% filter(New.PT2 == "New"))$total) / sum((wait_time_new$total))),0))
#   new_inPerson_14days <- as.character(sum((wait_time_new %>% filter(New.PT2 == "New" & Visit.Method == "IN PERSON" & group %in% c("0-7","8-14")))$perc))
#   new_tele_14days <- as.character(sum((wait_time_new %>% filter(New.PT2 == "New" & Visit.Method == "TELEHEALTH" & group %in% c("0-7","8-14")))$perc))
#   
#   dept_med_waitTime <- as.character(unique(as.numeric((wait_time_new %>% filter(New.PT2 == "New"))$med_wait)))
#   
#   key_list <- list(new_pt_vol, new_pt_vol_perc, new_inPerson_14days, new_tele_14days, dept_med_waitTime)
#   
#   return(key_list)
# }

```


```{r Referral Volume Table Output, echo = FALSE, warning = FALSE, message = FALSE}

conversion_rate_function <- function(department){
  
  # department <- "Medicine - Liver"
  conversion_data <- monthly_referral_vol %>%
    filter(Specialty == department) %>%
    filter(Received.YearQtr %in% reporting_YearQtr) 
    
  
  conversion_rate <- conversion_data %>%
    group_by(Campus, ApptStatusFinal) %>%
    summarise(total = sum(total)) %>%
    group_by(Campus) %>%
    pivot_wider(names_from = ApptStatusFinal,
                values_from = total, 
                values_fill = 0) %>%
    mutate(Total = rowSums(across(where(is.numeric)))) %>%
    mutate(Closed = Total - Pending) %>%
    mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
           `Completion Rate` = round(Arrived/Total,2)*100) 
  col_order <- c("Campus", "Total", "Closed", "Arrived", "No Show", "Canceled", "Scheduled", "Conversion Rate", "Completion Rate")
  col_order <- col_order[which(col_order %in% colnames(conversion_rate))]
  
  conversion_rate <- conversion_rate[,match(col_order, colnames(conversion_rate))]
  
  
  
  conversion_rate_mshs <- conversion_data %>%
    mutate(Campus = "Total") %>%
    group_by(Campus, ApptStatusFinal) %>%
    summarise(total = sum(total)) %>%
    group_by(Campus) %>%
    pivot_wider(names_from = ApptStatusFinal,
                values_from = total, 
                values_fill = 0) %>%
    mutate(Total = rowSums(across(where(is.numeric)))) %>%
    mutate(Closed = Total - Pending) %>%
    mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
           `Completion Rate` = round(Arrived/Total,2)*100)
  col_order <- c("Campus", "Total", "Closed", "Arrived", "No Show", "Canceled", "Scheduled", "Conversion Rate", "Completion Rate")
  col_order <- col_order[which(col_order %in% colnames(conversion_rate))]
  
  conversion_rate_mshs <- conversion_rate_mshs[,match(col_order, colnames(conversion_rate_mshs))]

  
  conversion_rate <- bind_rows(conversion_rate, conversion_rate_mshs)
  conversion_rate <- conversion_rate %>%
    rename(`Total Referrals Received` = Total,
           `Total Referrals Worked` = Closed,
           `Conversion Rate (Scheduled Appts)` = `Conversion Rate`,
           `Completion Rate (Arrived Appts)` = `Completion Rate`)
  
  # Table Output
  tbl_output <- 
    conversion_rate %>%
    flextable() %>%
    autofit() %>%
    fontsize(size = 14, part = "all") %>%
    font(fontname = "Calibri", part = "all") %>%
    vline(j = length(conversion_rate)-2, border = fp_border(color="grey", width = 0.5), part="body") %>%
    hline(i = nrow(conversion_rate)-1, border = fp_border(color="grey", width = 2), part="body") %>%
    bold(j = c(1:(length(conversion_rate))), part = "header") %>%
    bold(j = c(1,(length(conversion_rate)-1):(length(conversion_rate))), part = "all") %>%
    # surround(border.bottom = fp_border(color = "gray"), part = "all") %>%
    # surround(i = 1, border.bottom = fp_border(color = "black"), part = "header") %>%
    # surround(j = c(3:(length(overview_tbl)-1)), border.left = fp_border(color = "gray"), part = "all") %>%
    colformat_double(
     j = c((length(conversion_rate)-1):(length(conversion_rate))),
     digits = 0,
     suffix = "%") %>%
    align(j = c(2:(length(conversion_rate))), align = "center", part = "all") %>%
    bg(j = c(1:7), bg = "#212070", part = "header") %>%
    bg(j = c((length(conversion_rate)-1):(length(conversion_rate))), bg = "#d80b8c", part = "header") %>%
    color(j = c(1:length(conversion_rate)), color = "white", part = "header") %>%
    width(j = 1, width = 1.8) %>%
    width(j = c(2:3), width = 1.5) %>%
    width(j = c((length(conversion_rate)-1):(length(conversion_rate)-1)), width = 1.8) %>%
    width(j = c(4:(length(conversion_rate)-2)), width = 1) 
  
  return(tbl_output)
}


# conversion_rate_function_sub <- function(department){
#    
#   conversion_data <- monthly_referral_vol %>%
#     filter(Campus %!in% c("MSDD","NETWORK")) %>%
#     filter(Campus.Specialty.SubGroup == department) %>%
#     filter(Received.YearQtr %in% reporting_YearQtr) %>%
#     mutate(AppointmentStatus = ifelse(AppointmentStatus == "Completed", "Arrived",
#                                       ifelse(AppointmentStatus == "Left without seen", "No Show", AppointmentStatus))) 
#   
#   conversion_rate <- conversion_data %>%
#     group_by(Campus, AppointmentStatus) %>%
#     summarise(total = sum(total)) %>%
#     group_by(Campus) %>%
#     pivot_wider(names_from = AppointmentStatus,
#                 values_from = total, 
#                 values_fill = 0) %>%
#     mutate(Total = sum(c_across(Arrived:Scheduled))) %>%
#     mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
#            `Completion Rate` = round(Arrived/Total,2)*100) %>%
#     dplyr::select(Campus, Total, Arrived, `No Show`, Canceled, Scheduled, `Conversion Rate`, `Completion Rate`)
# 
#   
#   
#   conversion_rate_mshs <- conversion_data %>%
#     mutate(Campus = "Total") %>%
#     group_by(Campus, AppointmentStatus) %>%
#     summarise(total = sum(total)) %>%
#     group_by(Campus) %>%
#     pivot_wider(names_from = AppointmentStatus,
#                 values_from = total, 
#                 values_fill = 0) %>%
#     mutate(Total = sum(c_across(Arrived:Scheduled))) %>%
#     mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
#            `Completion Rate` = round(Arrived/Total,2)*100) %>%
#     dplyr::select(Campus, Total, Arrived, `No Show`, Canceled, Scheduled, `Conversion Rate`, `Completion Rate`)
#   
#   
#   conversion_rate <- bind_rows(conversion_rate, conversion_rate_mshs)
#   conversion_rate <- conversion_rate %>%
#     rename(`Total Referrals Received` = Total)
#   
#   # Table Output
#   tbl_output <- 
#     conversion_rate %>%
#     flextable() %>%
#     autofit() %>%
#     fontsize(size = 14, part = "all") %>%
#     font(fontname = "Calibri", part = "all") %>%
#     vline(j = c(6), border = fp_border(color="grey", width = 0.5), part="body") %>%
#     hline(i = nrow(conversion_rate)-1, border = fp_border(color="grey", width = 2), part="body") %>%
#     bold(j = c(1:(length(conversion_rate))), part = "header") %>%
#     bold(j = c(1, 7:8), part = "all") %>%
#     # surround(border.bottom = fp_border(color = "gray"), part = "all") %>%
#     # surround(i = 1, border.bottom = fp_border(color = "black"), part = "header") %>%
#     # surround(j = c(3:(length(overview_tbl)-1)), border.left = fp_border(color = "gray"), part = "all") %>%
#     colformat_double(
#      j = c(7:8),
#      digits = 0,
#      suffix = "%") %>%
#     align(j = c(2:(length(conversion_rate))), align = "center", part = "all") %>%
#     bg(j = c(1:6), bg = "#212070", part = "header") %>%
#     bg(j = c(7:8), bg = "#d80b8c", part = "header") %>%
#     color(j = c(1:length(conversion_rate)), color = "white", part = "header") %>%
#     width(j = 1, width = 2) %>%
#     width(j = c(2, 7:8), width = 1.5) %>%
#     width(j = c(3:(length(conversion_rate)-2)), width = 1) 
#   
#   return(tbl_output)
#   
# }

```


```{r Productivity and Wait Time Graph Output, echo = FALSE, warning = FALSE, message = FALSE}

# productivity_scatter_function <- function(department){
#   
#   waitTime_prod_output <- waitTime_prov %>%
#     filter(Specialty == department) %>%
#     filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
#     mutate(productivity = round(Productivity,2)*100) %>%
#     mutate(productivity_group = case_when(productivity < 50 ~ "Below P50",
#                                        productivity >=50 & productivity <75 ~ "P50-74",
#                                        TRUE ~ "Above P75")) 
#   
#   ggplot(waitTime_prod_output, aes(x=productivity, y=med_wait, color=productivity_group))+
#     geom_point(size = 4, alpha = 0.6)+
#     scale_color_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000","#7030a0","#5753d0","#5cd3ff"))+
#     labs(title = "Physician Productivity vs. Time to Appointment",
#          x = "2022 YTD Productivity",
#          y = "Median Time to Appointment (New)",
#          subtitle = department)+
#     # scale_y_continuous(limits = c(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1)), 
#     #                    breaks = seq(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1), by = .1),
#     #                    expand=c(0,0), labels = scales::percent_format(accuracy = 1))+
#     theme_bw()+
#       theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="10"),
#             legend.direction = "horizontal",
#             # legend.key.size = unit(1.0,"cm"),
#             legend.title = element_blank(),
#             axis.title = element_text(size="10"),
#             axis.text = element_text(size="10"),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     guides(colour = guide_legend(nrow = 1))
#   
# }

```


```{r Productivity and Wait Time Table Output, echo = FALSE, warning = FALSE, message = FALSE}

# productivity_table_function <- function(department){
#   
#   waitTime_prod_summary <- waitTime_prov %>%
#     filter(Specialty == department) %>%
#     filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
#     mutate(productivity = round(Productivity,2)*100) %>%
#     mutate(waitTime_group = case_when(med_wait >= 0 & med_wait <=7 ~ "0-7",
#                            med_wait >7 & med_wait <=14 ~ "8-14",
#                            med_wait >14 & med_wait <=30 ~ "15-30",
#                            TRUE ~ ">30"),
#            productivity_group = case_when(productivity < 50 ~ "0-49%",
#                            productivity >=50 & productivity <75 ~ "50-74%",
#                            productivity >=75 & productivity <=100 ~ "75-100%",
#                            TRUE ~ ">100%")) %>%
#     filter(!is.na(productivity)) %>%
#     group_by(waitTime_group, productivity_group) %>%
#     summarise(total = n()) %>%
#     pivot_wider(names_from = productivity_group,
#                 values_from = total,
#                 values_fill = 0)
#   
#   nms <- c("waitTime_group", "0-49%","50-74%","75-100%",">100%")
#   Missing <- setdiff(nms, names(waitTime_prod_summary))  # Find names of missing columns
#   waitTime_prod_summary[Missing] <- 0                    # Add them, filled with '0's
#   waitTime_prod_summary <- waitTime_prod_summary[nms] 
# 
#   waitTime_prod_summary <- waitTime_prod_summary %>%  
#     dplyr::select(waitTime_group, "0-49%","50-74%","75-100%",">100%") %>%
#     arrange(factor(waitTime_group, levels = c("0-7","8-14","15-30",">30"))) %>%
#     mutate(Total = rowSums(across(where(is.numeric)))) %>%
#     rename(`Median Days by % Productivity` = waitTime_group)
#     
#     Total <- colSums(waitTime_prod_summary[,2:length(waitTime_prod_summary)])
#     
#     waitTime_prod_summary <- bind_rows(waitTime_prod_summary, Total)
#     waitTime_prod_summary$`Median Days by % Productivity`[is.na(waitTime_prod_summary$`Median Days by % Productivity`)] <- "Total"
#     
#     tbl_output <- 
#       flextable(waitTime_prod_summary) %>%
#       fontsize(size = 12, part = "all") %>%
#       align(align = "center", part = "all") %>%
#       colformat_double(
#         j = 2:length(waitTime_prod_summary),
#         big.mark=",",
#         digits = 0) %>%
#       autofit() %>%
#       bold(j = c(1), part = "all") %>%
#       bg(j = c(2:length(waitTime_prod_summary)), bg = "#212070", part = "header") %>%
#       bg(j = 1, bg = "#e5e6e5", part = "body") %>%
#       color(j = c(2:length(waitTime_prod_summary)), color = "white", part = "header") %>%
#       color(j = 1, i = 1:nrow(waitTime_prod_summary), color = "black", part = "body") %>%
#       vline(j = 1, border = fp_border(width = 2, color = "#656765")) %>%
#       hline(i = c((nrow(waitTime_prod_summary)-1)), border = fp_border(width = 2, color = "#656765")) %>%
#       vline(j = c((length(waitTime_prod_summary)-1)), border = fp_border(width = 2, color = "#656765")) %>%
#       width(j = 1, width = 1.6) %>%
#       width(j = 2:length(waitTime_prod_summary), width = 0.9)
#       # width(j = c(2), width = 1) %>%
#       # width(j = c(3:length(payer_mix)), width = 1.2) %>%
#       # height(height = .4, part = "body")
#     # rotate(j = c(3:length(payer_mix)), rotation = "lrtb", align = "bottom", part = "header")
#     
# }

```


```{r Physician Productivity Output, echo = FALSE, warning = FALSE, message = FALSE}

productivity_provider_50_function <- function(department){
  # department <- "Medicine - Clinical Immunology"
  provider_list <- unique((waitTime_prov %>% 
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  provider_list <- provider_list %>% filter(!is.na(NPI))
  
  
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct() 
  
  productivity_tbl <- productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    dplyr::select(-c(NPI, Quarter, Productivity, Campus, Specialty, med_wait)) %>%
    distinct() %>%
    filter(`2022 Reported CFTE` >=0.25) %>%
    mutate(`2021 Calculate %` = `2021 Calculate %`*100,
           `2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2),
           Variance = `2022 Calculate %`-`2021 Calculate %`) 
  
  
  if(nrow(productivity_tbl) <1){
    productivity_tbl[1,] <- NA
    
  }
  
    
  tbl_output_50 <-
    productivity_tbl %>%
    filter(`2022 Calculate %` <50) %>%
    arrange(`2022 Calculate %`) %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(4:5, 8:9, 13),
        big.mark=",",
        digits = 0) %>%
    colformat_double(
        j = c(12),
        digits = 2) %>%
    colformat_double(
        j = c(14:16),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(6:7, 10:11),
        digits = 0,
        prefix = "$") %>%
    colformat_double(
        ~ Variance >=0, ~ Variance,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ Variance <0, ~ Variance,
        prefix = "-",
        suffix = "%",
        digit = 0) %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:7, 12:13), bg = "#00aeef", part = "header") %>%
    bg(j = c(8:11), bg = "#a5a7a5", part = "header") %>%
    bg(j = c(14:16), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:16), part = "header") %>%
    color(j = c(1:16), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:7, 12:16), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` >=75, ~ `2021 Calculate %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` <75, ~ `2021 Calculate %`, color = "red") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    color(~ Variance >=0, ~ Variance, color = "#00b800") %>%
    color(~ Variance <0, ~ Variance, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), 1.3) %>%
    width(j = c(4:11), width = 0.8) %>%
    width(j = c(12:16), width = 0.7) 
    
    
  return(tbl_output_50)
 
}



productivity_provider_75_function <- function(department){
  
  provider_list <- unique((waitTime_prov %>% 
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  provider_list <- provider_list %>% filter(!is.na(NPI))
  
  
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct()
  
  
  productivity_tbl <- productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    dplyr::select(-c(NPI, Quarter, Productivity, Campus, Specialty, med_wait)) %>%
    distinct() %>%
    filter(`2022 Reported CFTE` >=0.25) %>%
    mutate(`2021 Calculate %` = `2021 Calculate %`*100,
           `2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2),
           Variance = `2022 Calculate %`-`2021 Calculate %`) 
  
  
  if(nrow(productivity_tbl) <1){
    productivity_tbl[1,] <- NA
    
  }
  
    
  tbl_output_75 <-
    productivity_tbl %>%
    filter((`2022 Calculate %` >=50 & `2022 Calculate %` <75)) %>%
    arrange(`2022 Calculate %`) %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(4:5, 8:9, 13),
        big.mark=",",
        digits = 0) %>%
    colformat_double(
        j = c(12),
        digits = 2) %>%
    colformat_double(
        j = c(14:16),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(6:7, 10:11),
        digits = 0,
        prefix = "$") %>%
    colformat_double(
        ~ Variance >=0, ~ Variance,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ Variance <0, ~ Variance,
        prefix = "-",
        suffix = "%",
        digit = 0) %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:7, 12:13), bg = "#00aeef", part = "header") %>%
    bg(j = c(8:11), bg = "#a5a7a5", part = "header") %>%
    bg(j = c(14:16), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:16), part = "header") %>%
    color(j = c(1:16), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:7, 12:16), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` >=75, ~ `2021 Calculate %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` <75, ~ `2021 Calculate %`, color = "red") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    color(~ Variance >=0, ~ Variance, color = "#00b800") %>%
    color(~ Variance <0, ~ Variance, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), 1.3) %>%
    width(j = c(4:11), width = 0.8) %>%
    width(j = c(12:16), width = 0.7) 
    
    
  return(tbl_output_75)
 
}

productivity_provider_100_function <- function(department){
  
  provider_list <- unique((waitTime_prov %>% 
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  provider_list <- provider_list %>% filter(!is.na(NPI))
  
  
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct()
  
  productivity_tbl <- productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    dplyr::select(-c(NPI, Quarter, Productivity, Campus, Specialty, med_wait)) %>%
    distinct() %>%
    filter(`2022 Reported CFTE` >=0.25) %>%
    mutate(`2021 Calculate %` = `2021 Calculate %`*100,
           `2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2),
           Variance = `2022 Calculate %`-`2021 Calculate %`) 
  
  
  if(nrow(productivity_tbl) <1){
    productivity_tbl[1,] <- NA
    
  }
  
    
  tbl_output_100 <-
    productivity_tbl %>%
    filter(`2022 Calculate %` >=75) %>%
    arrange(`2022 Calculate %`) %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(4:5, 8:9, 13),
        big.mark=",",
        digits = 0) %>%
    colformat_double(
        j = c(12),
        digits = 2) %>%
    colformat_double(
        j = c(14:16),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(6:7, 10:11),
        digits = 0,
        prefix = "$") %>%
    colformat_double(
        ~ Variance >=0, ~ Variance,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ Variance <0, ~ Variance,
        prefix = "-",
        suffix = "%",
        digit = 0) %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:7, 12:13), bg = "#00aeef", part = "header") %>%
    bg(j = c(8:11), bg = "#a5a7a5", part = "header") %>%
    bg(j = c(14:16), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:16), part = "header") %>%
    color(j = c(1:16), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:7, 12:16), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` >=75, ~ `2021 Calculate %`, color = "#00b800") %>%
    color(~ `2021 Calculate %` <75, ~ `2021 Calculate %`, color = "red") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    color(~ Variance >=0, ~ Variance, color = "#00b800") %>%
    color(~ Variance <0, ~ Variance, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), 1.3) %>%
    width(j = c(4:11), width = 0.8) %>%
    width(j = c(12:16), width = 0.7) 
    
    
  return(tbl_output_100)
 
}

```


```{r Provider Access Output, echo = FALSE, warning = FALSE, message = FALSE}

access_provider_50_function <- function(department){
  
  # department <- "Dermatology"

  provider_list <- waitTime_prov %>%
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK"))

  productivity_wait_tbl <- merge((productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    filter(Quarter == reporting_YearQtr) %>%
    dplyr::select(`Master Dept`, Site, Physician, NPI, `2022 Reported CFTE`, `2022 FTE RVUs`, `2022 Calculate %`) %>%
    distinct()),
    provider_list[,c("NPI","Provider","Campus","Specialty","med_wait")],
    by = c("NPI")
  )
  
  # provider_list <- unique((waitTime_prov %>% 
  #                            filter(Specialty == department) %>%
  #                            filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
  #                            filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  # provider_list <- provider_list %>% filter(!is.na(NPI))
  # 
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct()
  
  productivity_wait_tbl <- productivity_wait_tbl %>% 
    mutate(`2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
    pivot_wider(names_from = Campus:Specialty,
                values_from = med_wait) %>%
    filter(`2022 Calculate %` <50) %>%
    dplyr::select(-c(NPI, Provider)) %>%
    arrange(`2022 Calculate %`)
  
  
  if(nrow(productivity_wait_tbl) <= 0){
    
   productivity_wait_tbl[1,] <- NA
   productivity_wait_tbl$`Median Wait Time` <- NA
  
  } 

  

  tbl_output_50 <-
    productivity_wait_tbl %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(5),
        digits = 0) %>%
    colformat_double(
        j = c(6),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(7:length(productivity_wait_tbl)),
        digits = 0,
        suffix = " days") %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:6), bg = "#00aeef", part = "header") %>%
    bg(j = c(7:length(productivity_wait_tbl)), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:length(productivity_wait_tbl)), part = "header") %>%
    color(j = c(1:length(productivity_wait_tbl)), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:length(productivity_wait_tbl)), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), width = 1.8) %>%
    width(j = c(4:length(productivity_wait_tbl)), width = 0.8)
    
    
  return(tbl_output_50)
  
  
 
}



access_provider_75_function <- function(department){
  
   provider_list <- waitTime_prov %>%
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK"))

  productivity_wait_tbl <- merge((productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    filter(Quarter == reporting_YearQtr) %>%
    dplyr::select(`Master Dept`, Site, Physician, NPI, `2022 Reported CFTE`, `2022 FTE RVUs`, `2022 Calculate %`) %>%
    distinct()),
    provider_list[,c("NPI","Provider","Campus","Specialty","med_wait")],
    by = c("NPI")
  )
  
  # provider_list <- unique((waitTime_prov %>% 
  #                            filter(Specialty == department) %>%
  #                            filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
  #                            filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  # provider_list <- provider_list %>% filter(!is.na(NPI))
  # 
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct()
  
  productivity_wait_tbl <- productivity_wait_tbl %>% 
    mutate(`2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
    pivot_wider(names_from = Campus:Specialty,
                values_from = med_wait) %>%
    filter((`2022 Calculate %` >=50 & `2022 Calculate %` <75)) %>%
    dplyr::select(-c(NPI, Provider)) %>%
    arrange(`2022 Calculate %`)
  
  
  if(nrow(productivity_wait_tbl) <= 0){
    
   productivity_wait_tbl[1,] <- NA
   productivity_wait_tbl$`Median Wait Time` <- NA
  } 

  

  
  tbl_output_75 <-
    productivity_wait_tbl %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(5),
        digits = 0) %>%
    colformat_double(
        j = c(6),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(7:length(productivity_wait_tbl)),
        digits = 0,
        suffix = " days") %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:6), bg = "#00aeef", part = "header") %>%
    bg(j = c(7:length(productivity_wait_tbl)), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:length(productivity_wait_tbl)), part = "header") %>%
    color(j = c(1:length(productivity_wait_tbl)), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:length(productivity_wait_tbl)), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), width = 1.8) %>%
    width(j = c(4:length(productivity_wait_tbl)), width = 0.8)
    
    
  return(tbl_output_75)

 
}


access_provider_100_function <- function(department){
  
  provider_list <- waitTime_prov %>%
                             filter(Specialty == department) %>%
                             filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
                             filter(Campus %!in% c("MSDD","NETWORK"))

  productivity_wait_tbl <- merge((productivity_raw %>%
    filter(NPI %in% unique(provider_list$NPI)) %>%
    filter(Quarter == reporting_YearQtr) %>%
    dplyr::select(`Master Dept`, Site, Physician, NPI, `2022 Reported CFTE`, `2022 FTE RVUs`, `2022 Calculate %`) %>%
    distinct()),
    provider_list[,c("NPI","Provider","Campus","Specialty","med_wait")],
    by = c("NPI")
  )
  
  # provider_list <- unique((waitTime_prov %>% 
  #                            filter(Specialty == department) %>%
  #                            filter(Appt.Made.YearQtr == reporting_YearQtr) %>%
  #                            filter(Campus %!in% c("MSDD","NETWORK")))[,c("Provider","NPI")])
  # provider_list <- provider_list %>% filter(!is.na(NPI))
  # 
  # Subset raw productivity data 
  # productivity_tbl <- productivity_raw %>%
  #   filter(Quarter == reporting_YearQtr) %>%
  #   filter(NPI %in% unique(provider_list$NPI)) %>%
  #   dplyr::select(-c(NPI, Quarter, Campus, Specialty, med_wait)) %>%
  #   mutate(Productivity = Productivity*100,
  #          `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
  #   distinct()
  
  productivity_wait_tbl <- productivity_wait_tbl %>% 
    mutate(`2022 Calculate %` = `2022 Calculate %`*100,
           `2022 Reported CFTE` = round(as.numeric(`2022 Reported CFTE`),2)) %>%
    pivot_wider(names_from = Campus:Specialty,
                values_from = med_wait) %>%
    filter(`2022 Calculate %` >=75) %>%
    dplyr::select(-c(NPI, Provider)) %>%
    arrange(`2022 Calculate %`)
  
  
  if(nrow(productivity_wait_tbl) <= 0){
    
  productivity_wait_tbl[1,] <- NA
   productivity_wait_tbl$`Median Wait Time` <- NA
  
  } 

  

  
  tbl_output_100 <-
    productivity_wait_tbl %>%
    flextable() %>%
    fontsize(size = 8, part = "all") %>%
    autofit() %>%
    colformat_double(
        j = c(5),
        digits = 0) %>%
    colformat_double(
        j = c(6),
        digits = 0,
        suffix = "%") %>%
    colformat_double(
        j = c(7:length(productivity_wait_tbl)),
        digits = 0,
        suffix = " days") %>%
    theme_vanilla() %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:6), bg = "#00aeef", part = "header") %>%
    bg(j = c(7:length(productivity_wait_tbl)), bg = "#d80b8c", part = "header") %>%
    bold(j = c(1:length(productivity_wait_tbl)), part = "header") %>%
    color(j = c(1:length(productivity_wait_tbl)), color = "white", part = "header") %>%
    # bg(j = c(12:13), bg = colourer, part = "body") %>%
    bold(j = c(4:length(productivity_wait_tbl)), part = "body") %>%
    # color(~ `Percent Increase/Decrease` < 0, ~ `Percent Increase/Decrease`, color = "red") %>%
    # color(~ `Percent Increase/Decrease` > 0, ~ `Percent Increase/Decrease`, color = "#00b800") %>%
    # color(~ `2021 Calculated %` < 75, ~ `2021 Calculated %`, color = "red") %>%
    # color(~ `2021 Calculated %` >= 75, ~ `2021 Calculated %`, color = "#00b800") %>%
    # color(~ `2022 Calculated %` < 75, ~ `2022 Calculated %`, color = "red") %>%
    # color(~ `2022 Calculated %` >= 75, ~ `2022 Calculated %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` >=75, ~ `2022 Calculate %`, color = "#00b800") %>%
    color(~ `2022 Calculate %` <75, ~ `2022 Calculate %`, color = "red") %>%
    height(height = .3, part = "body") %>%
    width(j = c(1,3), width = 1.8) %>%
    width(j = c(4:length(productivity_wait_tbl)), width = 0.8)
    
    
  return(tbl_output_100)
 
}

```


```{r Overall Utilization Table Output, echo = FALSE, warning = FALSE, message = FALSE}

# # MSHS Utilization Table Output - Day 
# overall_day_util_tbl_function <- function(department){
#   
#   # department <- "ENT-Otolaryngology"
#   
#   # MSHS Utilization
#   weekday_util_mshs_tbl <- weekday_metrics_merged_mshs %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)], data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
#     arrange(desc(Appt.YearQtr)) %>%
#     arrange(Metric, Breakdown) %>%
#     group_by(Metric, Breakdown) %>%
#     mutate(prior_value = shift(Value)) %>%
#     mutate(prior_value = ifelse(is.na(prior_value), Value, prior_value)) %>%
#     mutate(prior_value = ifelse(is.na(prior_value), Value, shift(prior_value))) %>%
#     mutate(diff = ifelse(is.na(prior_value), Value, prior_value - Value)) %>%
#     dplyr::select(-c(Value, prior_value)) %>%
#     rename(Value = diff) %>%
#     pivot_wider(names_from = Metric,
#                 values_from = Value) %>%
#     # mutate(Campus = "MSHS") %>%
#     mutate(Appt.YearQtr = as.character(as.yearqtr(Appt.YearQtr))) %>%
#     dplyr::select(Appt.YearQtr, Breakdown, room_count, Benchmark, 
#                   daily_vol, vol_target_var, visits_util, dur_utilization)
#   
#   current_qtr <- weekday_util_mshs_tbl %>%
#     filter(Appt.YearQtr == data_quarters[length(data_quarters)]) %>%
#     dplyr::select(-Appt.YearQtr)
#   
#   previous_qtr <- weekday_util_mshs_tbl %>%
#     filter(Appt.YearQtr == data_quarters[length(data_quarters)-1]) %>%
#     dplyr::select(-Appt.YearQtr)
#   
#   site <- data.frame(Campus = rep("MSHS Overall",3))
#   data_mshs <- merge(previous_qtr, current_qtr, by = c("Breakdown","room_count","Benchmark"))
#   data_mshs <- bind_cols(site, data_mshs)
#   
#   data_mshs <- data_mshs %>%
#     arrange(factor(Breakdown, levels = c("Day","AM","PM"))) 
#   
#   
#   # Utilization by Site
#   weekday_util_site_tbl <- weekday_metrics_merged_site %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)], data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
#     arrange(desc(Appt.YearQtr)) %>%
#     arrange(Metric, Breakdown, Campus) %>%
#     group_by(Metric, Breakdown, Campus) %>%
#     mutate(prior_value = shift(Value)) %>%
#     mutate(prior_value = ifelse(is.na(prior_value), Value, prior_value)) %>%
#     mutate(prior_value = ifelse(is.na(prior_value), Value, shift(prior_value))) %>%
#     mutate(diff = ifelse(is.na(prior_value), Value, prior_value - Value)) %>%
#     dplyr::select(-c(Value, prior_value)) %>%
#     rename(Value = diff) %>%
#     pivot_wider(names_from = Metric,
#                 values_from = Value) %>%
#     # mutate(Campus = "MSHS") %>%
#     mutate(Appt.YearQtr = as.character(as.yearqtr(Appt.YearQtr))) %>%
#     dplyr::select(Appt.YearQtr, Campus, Breakdown, room_count, Benchmark, 
#                   daily_vol, vol_target_var, visits_util, dur_utilization)
#   
#   
#   current_qtr <- weekday_util_site_tbl %>%
#     filter(Appt.YearQtr == data_quarters[length(data_quarters)]) %>%
#     dplyr::select(-Appt.YearQtr)
#   
#   previous_qtr <- weekday_util_site_tbl %>%
#     filter(Appt.YearQtr == data_quarters[length(data_quarters)-1]) %>%
#     dplyr::select(-Appt.YearQtr)
#   
#   data_site <- merge(previous_qtr, current_qtr, by = c("Campus","Breakdown","room_count","Benchmark"))
#   data_site <- data_site %>%
#     arrange(factor(Breakdown, levels = c("Day","AM","PM"))) %>%
#     arrange(Campus)
#   
#   data <- bind_rows(data_mshs, data_site)
#   
#   is.nan.data.frame <- function(x)
#     do.call(cbind, lapply(x, is.nan))
#   
#   data[is.nan(data)] <- NA
#   
#   colourer <- col_numeric(
#     palette = c("red", "wheat", "#00b800"),
#     domain = c(0, .5, 1))
#   
#   tbl_output <- flextable(data) %>%
#     autofit() %>%
#     fontsize(size = 11, part = "all") %>%
#     fontsize(size = 6, part = "footer") %>%
#     font(fontname = "Calibri", part = "all") %>%
#     italic(part = "footer") %>%
#     colformat_double(
#       j = c(5:length(data)),
#       big.mark=",",
#       digits = 0) %>%
#     add_header_row(values = c("","Previous Quarter", "Current Quarter"), colwidths = c(4,4,4)) %>%
#     add_footer_lines("Utilization Target: 85%") %>%
#     bold(j = c(1, 7:8, 11:12), part = "all") %>%
#     align(j = c(1:2), align = "left", part = "all") %>%
#     # color(j = c(1:4), color = "black", part = "all") %>%
#     # color(~ visits_util.x < .85, ~ visits_util.x, color = "red") %>%
#     # color(~  dur_utilization.x < .85, ~  dur_utilization.x, color = "red") %>%
#     # color(~ visits_util.x >= .85, ~ visits_util.x, color = "#00b800") %>%
#     # color(~ dur_utilization.x >= .85, ~ dur_utilization.x, color = "#00b800") %>%
#     # color(~ visits_util.y < .85, ~ visits_util.y, color = "red") %>%
#     # color(~  dur_utilization.y < .85, ~  dur_utilization.y, color = "red") %>%
#     # color(~ visits_util.y >= .85, ~ visits_util.y, color = "#00b800") %>%
#     # color(~ dur_utilization.y >= .85, ~ dur_utilization.y, color = "#00b800") %>%
#     bg(j = c(7:8,11:12), bg = colourer, part = "body") %>%
#     set_formatter(visits_util.x = function(x) sprintf( "%.0f%%", as.numeric(x)*100),
#                   dur_utilization.x = function(x) sprintf( "%.0f%%", as.numeric(x)*100),
#                   visits_util.y = function(x) sprintf( "%.0f%%", as.numeric(x)*100),
#                   dur_utilization.y = function(x) sprintf( "%.0f%%", as.numeric(x)*100)) %>%
#     bg(j = c(5:8), bg = "#7f7f7f", part = "header") %>%
#     bg(j = c(5:6), bg = "#F0F0F0", part = "body") %>%
#     bg(j = c(9:12), bg = "#212070", part = "header") %>%
#     bg(j = c(9:10), bg ="#EBEBF9", part = "body") %>%
#     set_header_labels(Campus = "Site", Breakdown = "Session", room_count = "Total Rooms", Benchmark = "Visits/Room/Day Benchmark",
#                       daily_vol.x = "Avg Weekday Visits", vol_target_var.x = "Var from Benchmark", 
#                       visits_util.x = "% Utilization (By Turns)", dur_utilization.x = "% Utilization (By Durations)",
#                       daily_vol.y = "Avg Weekday Visits", vol_target_var.y = "Var from Benchmark", 
#                       visits_util.y = "% Utilization (By Turns)", dur_utilization.y = "% Utilization (By Durations)") %>%
#     bold(j = 1:length(data), part = "header") %>%
#     merge_v(j = ~Campus) %>%
#     surround(border.bottom = fp_border(color = "gray"), part = "all") %>%
#     surround(i = 1, j = 1:4, border.top = fp_border(color = "white"), part = "header") %>%
#     align(j = 3:length(data), align = "center", part = "all") %>%
#     color(j = 5:length(data), color = "white", part = "header") %>%
#     height(height = 0.25, part = "body") %>%
#     width(j = 1, width = 1.5) %>%
#     width(j = 2:3, width = 0.7) %>%
#     width(j = 4, width = 1.2) %>%
#     width(j = 5:12, width = 1.1)
#   
#   return(tbl_output)
#   
# }


```



```{r MSHS Utilization by Hour Processing, echo = FALSE, warning = FALSE, message = FALSE}


# overall_weekday_util_hour <- function(department){
#   
#   # Summarize total time spent in room per provider
#   room_util_all <- util_data_raw %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.Day %!in% c("Sat","Sun")) %>%
#     dplyr::select(Campus.Specialty, Campus, Appt.Day,`08:00`:`17:00`) %>%
#     pivot_longer(`08:00`:`17:00`,
#                  names_to = "space_time",
#                  values_to = "space_dur") 
#   
#   
#   room_util_mshs <- room_util_all %>%
#     group_by(Campus.Specialty, Appt.Day, space_time) %>%
#     dplyr::summarise(total_space_dur = sum(space_dur, na.rm = TRUE))
#   
#   # Total Working days by provider
#   working_days_mshs <- util_data_raw  %>%
#     group_by(Appt.Day) %>%
#     dplyr::summarise(total_space_days = length(unique(Appt.DateYear)))
#   
#   room_util_mshs <- merge(room_util_mshs, working_days_mshs)
#   room_util_mshs <- merge(room_util_mshs, room_count_summary_mshs)
# 
#   # Utilization by Hour
#   avg_util_hour_mshs <- room_util_mshs %>%
#     mutate(avg_room_util = round(total_space_dur/total_space_days),
#            avg_space_required = ceiling(avg_room_util/60),
#            avg_perc_util = round(avg_room_util/(room_count*60),2))
#   
#   daysOfWeek.options <- c("Mon","Tue","Wed","Thu","Fri","Sat","Sun") ## Days of Week Filter
#   
#   # Average Utilizaton by Hour 
#   graph <- ggplot()+
#     # Create bounds for "under-utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 0,
#                   ymax = .85,
#                   fill = "Under",
#                   alpha = "Under"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = .85,
#                   ymax = 1,
#                   fill = "Well",
#                   alpha = "Well"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 1,
#                   ymax = Inf,
#                   fill = "Over",
#                   alpha = "Over"), show.legend = FALSE) +
#     scale_fill_manual(name = "Status",
#                       values = c("Under" = "red",
#                                  "Well" = "green",
#                                  "Over" = "orange"),
#                       breaks=c("Under", "Well", "Over")) +
#     scale_alpha_manual(name = "Status",
#                        values = c("Under" = 0.15,
#                                   "Well" = 0.15,
#                                   "Over" = 0.15))+
#     geom_point(data = avg_util_hour_mshs, aes(x=space_time, y=avg_perc_util, col=factor(Appt.Day,level = daysOfWeek.options), group=Appt.Day),
#                size = 2)+
#     geom_line(data = avg_util_hour_mshs, aes(x=space_time, y=avg_perc_util, col=factor(Appt.Day,level = daysOfWeek.options), group=Appt.Day),
#               size = 1)+
#     labs(title = "Average Utilization by Hour (Weekdays Only)",
#          subtitle = department)+
#     scale_y_continuous(limits = c(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1)), 
#                        breaks = seq(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1), by = .1),
#                        expand=c(0,0), labels = scales::percent_format(accuracy = 1))+
#     scale_color_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000"))+
#     theme_bw()+
#       theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="10"),
#             legend.direction = "horizontal",
#             # legend.key.size = unit(1.0,"cm"),
#             legend.title = element_blank(),
#             axis.title = element_blank(),
#             axis.text = element_text(size="10"),
#             axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))
#   
#   return(graph)
#   
# }
# 
# 
# overall_weekend_util_hour <- function(department){
#   
#   # Summarize total time spent in room per provider
#   room_util_all <- util_data_raw %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.Day %in% c("Sat","Sun")) %>%
#     dplyr::select(Campus.Specialty, Campus, Appt.Day,`08:00`:`17:00`) %>%
#     pivot_longer(`08:00`:`17:00`,
#                  names_to = "space_time",
#                  values_to = "space_dur") 
#   
#   
#   room_util_mshs <- room_util_all %>%
#     group_by(Campus.Specialty, Appt.Day, space_time) %>%
#     dplyr::summarise(total_space_dur = sum(space_dur, na.rm = TRUE))
#   
#   # Total Working days by provider
#   working_days_mshs <- util_data_raw  %>%
#     group_by(Appt.Day) %>%
#     dplyr::summarise(total_space_days = length(unique(Appt.DateYear)))
#   
#   room_util_mshs <- merge(room_util_mshs, working_days_mshs)
#   room_util_mshs <- merge(room_util_mshs, room_count_summary_mshs)
# 
#   # Utilization by Hour
#   avg_util_hour_mshs <- room_util_mshs %>%
#     mutate(avg_room_util = round(total_space_dur/total_space_days),
#            avg_space_required = ceiling(avg_room_util/60),
#            avg_perc_util = round(avg_room_util/(room_count*60),2))
#   
#   daysOfWeek.options <- c("Mon","Tue","Wed","Thu","Fri","Sat","Sun") ## Days of Week Filter
#   
#   # Average Utilizaton by Hour 
#   graph <- ggplot()+
#     # Create bounds for "under-utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 0,
#                   ymax = .85,
#                   fill = "Under",
#                   alpha = "Under"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = .85,
#                   ymax = 1,
#                   fill = "Well",
#                   alpha = "Well"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 1,
#                   ymax = Inf,
#                   fill = "Over",
#                   alpha = "Over"), show.legend = FALSE) +
#     scale_fill_manual(name = "Status",
#                       values = c("Under" = "red",
#                                  "Well" = "green",
#                                  "Over" = "orange"),
#                       breaks=c("Under", "Well", "Over")) +
#     scale_alpha_manual(name = "Status",
#                        values = c("Under" = 0.15,
#                                   "Well" = 0.15,
#                                   "Over" = 0.15))+
#     geom_point(data = avg_util_hour_mshs, aes(x=space_time, y=avg_perc_util, col=factor(Appt.Day,level = daysOfWeek.options), group=Appt.Day),
#                size = 2)+
#     geom_line(data = avg_util_hour_mshs, aes(x=space_time, y=avg_perc_util, col=factor(Appt.Day,level = daysOfWeek.options), group=Appt.Day),
#               size = 1)+
#     labs(title = "Average Utilization by Hour (Weekends)",
#          subtitle = department)+
#     scale_y_continuous(limits = c(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1)), 
#                        breaks = seq(0,max(1,max(avg_util_hour_mshs$avg_perc_util)*1.1), by = .1),
#                        expand=c(0,0), labels = scales::percent_format(accuracy = 1))+
#     scale_color_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000"))+
#     theme_bw()+
#       theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="10"),
#             legend.direction = "horizontal",
#             # legend.key.size = unit(1.0,"cm"),
#             legend.title = element_blank(),
#             axis.title = element_blank(),
#             axis.text = element_text(size="10"),
#             axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))
#   
#   return(graph)
#   
# }

```


```{r Site Utilization by Hour Processing, echo = FALSE, warning = FALSE, message = FALSE}

# site_weekday_util_hour <- function(department){
#   
#   
#   # Summarize total time spent in room per provider
#   room_util_avg <- util_data_raw %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.Day %!in% c("Sat","Sun")) %>%
#     dplyr::select(Campus.Specialty, Campus,`08:00`:`17:00`) %>%
#     pivot_longer(`08:00`:`17:00`,
#                  names_to = "space_time",
#                  values_to = "space_dur") 
# 
#   
#   room_util_site <- room_util_avg %>%
#     group_by(Campus.Specialty, Campus, space_time) %>%
#     dplyr::summarise(total_space_dur = sum(space_dur, na.rm = TRUE))
# 
#   # Total Working days by provider
#   working_days_site <- util_data_raw  %>%
#     group_by(Campus) %>%
#     dplyr::summarise(total_space_days = length(unique(Appt.DateYear)))
# 
#   room_util_site <- merge(room_util_site, working_days_site)
#   room_util_site <- merge(room_util_site, room_count_summary_site)
# 
#   # Utilization by Hour
#   avg_util_hour_site <- room_util_site %>%
#     mutate(avg_room_util = round(total_space_dur/total_space_days),
#            avg_space_required = ceiling(avg_room_util/60),
#            avg_perc_util = round(avg_room_util/(room_count*60),2))
#   
#   
#   # Average Utilizaton by Hour 
#   graph <- ggplot()+
#     # Create bounds for "under-utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 0,
#                   ymax = .85,
#                   fill = "Under",
#                   alpha = "Under"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = .85,
#                   ymax = 1,
#                   fill = "Well",
#                   alpha = "Well"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 1,
#                   ymax = Inf,
#                   fill = "Over",
#                   alpha = "Over"), show.legend = FALSE) +
#     scale_fill_manual(name = "Status",
#                       values = c("Under" = "red",
#                                  "Well" = "green",
#                                  "Over" = "orange"),
#                       breaks=c("Under", "Well", "Over")) +
#     scale_alpha_manual(name = "Status",
#                        values = c("Under" = 0.15,
#                                   "Well" = 0.15,
#                                   "Over" = 0.15))+
#     geom_point(data = avg_util_hour_site, aes(x=space_time, y=avg_perc_util, col=Campus, group=Campus),
#                size = 2)+
#     geom_line(data = avg_util_hour_site, aes(x=space_time, y=avg_perc_util, col=Campus, group=Campus),
#               size = 1)+
#     labs(title = "Average Utilization by Site (Weekdays Only)",
#          subtitle = department)+
#     scale_y_continuous(limits = c(0,max(1,max(avg_util_hour_site$avg_perc_util)*1.1)), 
#                        breaks = seq(0,max(1,max(avg_util_hour_site$avg_perc_util*1.1)), by = .1),
#                        expand=c(0,0), labels = scales::percent_format(accuracy = 1))+
#     scale_color_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000","#7030a0","#5753d0","#5cd3ff"))+
#     theme_bw()+
#       theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="6"),
#             legend.direction = "horizontal",
#             # legend.key.size = unit(1.0,"cm"),
#             legend.title = element_blank(),
#             axis.title = element_blank(),
#             axis.text = element_text(size="10"),
#             axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     guides(colour = guide_legend(nrow = 1))
#   
#   return(graph)
#   
# }
# 
# 
# site_weekend_util_hour <- function(department){
#   
#   # department <- "ENT-Otolaryngology"
#   # Summarize total time spent in room per provider
#   room_util_avg <- util_data_raw %>%
#     filter(Campus.Specialty == department) %>%
#     filter(Appt.Day %in% c("Sat","Sun")) %>%
#     dplyr::select(Campus.Specialty, Campus,`08:00`:`17:00`) %>%
#     pivot_longer(`08:00`:`17:00`,
#                  names_to = "space_time",
#                  values_to = "space_dur") 
# 
#   
#   room_util_site <- room_util_avg %>%
#     group_by(Campus.Specialty, Campus, space_time) %>%
#     dplyr::summarise(total_space_dur = sum(space_dur, na.rm = TRUE))
# 
#   # Total Working days by provider
#   working_days_site <- util_data_raw  %>%
#     group_by(Campus) %>%
#     dplyr::summarise(total_space_days = length(unique(Appt.DateYear)))
# 
#   room_util_site <- merge(room_util_site, working_days_site)
#   room_util_site <- merge(room_util_site, room_count_summary_site)
# 
#   # Utilization by Hour
#   avg_util_hour_site <- room_util_site %>%
#     mutate(avg_room_util = round(total_space_dur/total_space_days),
#            avg_space_required = ceiling(avg_room_util/60),
#            avg_perc_util = round(avg_room_util/(room_count*60),2))
#   
#   
#   # Average Utilizaton by Hour 
#   graph <- ggplot()+
#     # Create bounds for "under-utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 0,
#                   ymax = .85,
#                   fill = "Under",
#                   alpha = "Under"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = .85,
#                   ymax = 1,
#                   fill = "Well",
#                   alpha = "Well"), show.legend = FALSE) +
#     # Create bounds for "well utilized" performance
#     geom_rect(aes(xmin = -Inf,
#                   xmax = Inf,
#                   ymin = 1,
#                   ymax = Inf,
#                   fill = "Over",
#                   alpha = "Over"), show.legend = FALSE) +
#     scale_fill_manual(name = "Status",
#                       values = c("Under" = "red",
#                                  "Well" = "green",
#                                  "Over" = "orange"),
#                       breaks=c("Under", "Well", "Over")) +
#     scale_alpha_manual(name = "Status",
#                        values = c("Under" = 0.15,
#                                   "Well" = 0.15,
#                                   "Over" = 0.15))+
#     geom_point(data = avg_util_hour_site, aes(x=space_time, y=avg_perc_util, col=Campus, group=Campus),
#                size = 2)+
#     geom_line(data = avg_util_hour_site, aes(x=space_time, y=avg_perc_util, col=Campus, group=Campus),
#               size = 1)+
#     labs(title = "Average Utilization by Site (Weekends)",
#          subtitle = department)+
#     scale_y_continuous(limits = c(0,max(1,max(avg_util_hour_site$avg_perc_util)*1.1)), 
#                        breaks = seq(0,max(1,max(avg_util_hour_site$avg_perc_util*1.1)), by = .1),
#                        expand=c(0,0), labels = scales::percent_format(accuracy = 1))+
#     scale_color_manual(values=c("#212070","#d80b8c","#00aeef","#7f7f7f","#ffc000","#7030a0","#5753d0","#5cd3ff"))+
#     theme_bw()+
#       theme(plot.title = element_text(hjust=0.5, face = "bold", size = 14),
#             plot.subtitle = element_text(hjust=0.5, size = 12, face = "italic"),
#             legend.position = "bottom",
#             legend.text = element_text(size="6"),
#             legend.direction = "horizontal",
#             # legend.key.size = unit(1.0,"cm"),
#             legend.title = element_blank(),
#             axis.title = element_blank(),
#             axis.text = element_text(size="10"),
#             axis.title.x = element_blank(),
#             axis.line = element_line(size = 0.3, colour = "black"))+
#     guides(colour = guide_legend(nrow = 1))
#   
#   return(graph)
#   
# }


```


```{r Payer Mix Output, echo=FALSE, message=FALSE, warning=FALSE}

dept_payer_mix <- function(department){

  payer_mix <- payer_mix_quarter_site %>%
    filter(Specialty == department) %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)],
                                 data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Specialty, Campus, Appt.YearQtr, Coverage) %>%
    summarise(payer = sum(payer)) %>%
    group_by(Specialty, Campus, Appt.YearQtr) %>%
    mutate(total_vol = sum(payer),
           payer_perc = round(payer/sum(payer),2)*100) %>%
    filter(Coverage == "Commercial/Managed Care") 
  
  total_payer_mix <- payer_mix %>%
    filter(Appt.YearQtr == reporting_YearQtr) %>%
    dplyr::select(-payer)
  
  payer_mix_var <- payer_mix %>%
    dplyr::select(-c(payer, total_vol)) %>%
    pivot_wider(names_from = Appt.YearQtr,
                values_from = payer_perc) %>%
    ungroup() %>%
    filter(!is.na(.[[6]])) %>%
    mutate(var_last_qrt = .[[6]] - .[[5]],
           var_last_yr = .[[6]] - .[[4]]) %>%
    dplyr::select(Specialty, Campus, Coverage, var_last_qrt, var_last_yr)
  
  payer_mix_var <- merge(total_payer_mix, payer_mix_var)
  
  
  # MSHS Total All Departments
  mshs_payer_mix <- payer_mix_quarter_site %>%
    filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)],
                                 data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
    mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
    group_by(Campus, Appt.YearQtr, Coverage) %>%
    summarise(payer = sum(payer)) %>%
    group_by(Campus, Appt.YearQtr) %>%
    mutate(total_vol_mshs = sum(payer),
           payer_perc_mshs = round(payer/sum(payer),2)*100) %>%
    filter(Coverage == "Commercial/Managed Care") 
  
  mshs_total_payer_mix <- mshs_payer_mix %>%
    filter(Appt.YearQtr == reporting_YearQtr) %>%
    dplyr::select(-payer)
  
  mshs_payer_mix_var <- mshs_payer_mix %>%
    dplyr::select(-c(payer, total_vol_mshs)) %>%
    pivot_wider(names_from = Appt.YearQtr,
                values_from = payer_perc_mshs) %>%
    ungroup() %>%
    filter(!is.na(.[[5]])) %>%
    mutate(var_last_qrt_mshs = .[[5]] - .[[4]],
           var_last_yr_mshs = .[[5]] - .[[3]]) %>%
    dplyr::select(Campus, Coverage, var_last_qrt_mshs, var_last_yr_mshs)
  
  mshs_payer_mix_var <- merge(mshs_total_payer_mix, mshs_payer_mix_var)
  
  payer_mix_var_merged <- merge(payer_mix_var, mshs_payer_mix_var)
  payer_mix_var_merged <-  payer_mix_var_merged %>%
    dplyr::select(-c(Appt.YearQtr, Specialty, Coverage, total_vol_mshs))
  
  cols <- c("Site", paste0(department," Volume in ",reporting_YearQtr), "% of Total Volume", 
           "Variance from Last Quarter", "Variance from Same Quarter Last Year",
            "% of All Departments Total", "All Departments Variance from Last Quarter", "All Departments Variance from Same Quarter Last Year")
  
  # cols <- c("Site", paste0(department," Volume in ",reporting_YearQtr), "% of Total Volume", 
  #           "Variance from Last Quarter", "Variance from Same Quarter Last Year",
  #           "% of Total Volume", "Variance from Last Quarter", "Variance from Same Quarter Last Year")
    
  colnames(payer_mix_var_merged) <- cols
  
 tbl_output <- 
   flextable(payer_mix_var_merged) %>%
   font(fontname = "Calibri", part = "all") %>%
   fontsize(size = 12, part = "all") %>%
   align(j = 1, align = "left", part = "all") %>%
   align(j = 2:length(payer_mix_var_merged), align = "center", part = "all") %>%
   add_header_row(values = c(" ",paste0(department,": % of Commercial/Managed Care Volume"), 
                             "All Departments: % of Commercial/Managed Care Volume"), colwidths = c(2,3,3)) %>%
  # align(j = 1, align = "left", part = "header") %>%
   colformat_double(
     j = c(3,6), 
     digits = 0,
     suffix = "%") %>%
   colformat_double(
      j = 2,
      big.mark=",",
      digits = 0) %>%
   colformat_double(
        ~ `Variance from Last Quarter`  >=0, ~ `Variance from Last Quarter`,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `Variance from Same Quarter Last Year`  >=0, ~ `Variance from Same Quarter Last Year`,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `All Departments Variance from Last Quarter`  >=0, ~ `All Departments Variance from Last Quarter`,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `All Departments Variance from Same Quarter Last Year`  >=0, ~ `All Departments Variance from Same Quarter Last Year`,
        prefix = "+",
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `Variance from Last Quarter`  <0, ~ `Variance from Last Quarter`,
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `Variance from Same Quarter Last Year`  <0, ~ `Variance from Same Quarter Last Year`,
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `All Departments Variance from Last Quarter`  <0, ~ `All Departments Variance from Last Quarter`,
        suffix = "%",
        digit = 0) %>%
    colformat_double(
        ~ `All Departments Variance from Same Quarter Last Year`  <0, ~ `All Departments Variance from Same Quarter Last Year`,
        suffix = "%",
        digit = 0) %>%
   autofit() %>%
   bold(j = c(1), part = "all") %>%
   bold(j = c(1:length(payer_mix_var_merged)), part = "header") %>%
   bold(j = c(4:5,7:8), part = "body") %>%
   # align(j = c(1), align = "left", part = "all") %>%
   bg(j = c(1:2), bg = "white", part = "header") %>%
   bg(j = c(3:5), bg = "#212070", part = "header") %>%
   bg(j = c(6:8), bg = "#d80b8c", part = "header") %>%
   color(j = c(1:length(payer_mix_var_merged)), color = "black", part = "body") %>%
   color(j = c(3:length(payer_mix_var_merged)), color = "white", part = "header") %>%
   # bg(bg = colourer,
   #    j = c(3:length(payer_mix)),
   #    i = c(1:(nrow(payer_mix))),
   #    part = "body") %>%
   vline(j = c(2,5), border = fp_border(width = 2, color = "#656765")) %>%
   color(~ `Variance from Last Quarter` >0, ~ `Variance from Last Quarter`, color = "#00b800") %>%
   color(~ `Variance from Last Quarter` <0, ~ `Variance from Last Quarter`, color = "red") %>%
   color(~ `Variance from Same Quarter Last Year` >0, ~ `Variance from Same Quarter Last Year`, color = "#00b800") %>%
   color(~ `Variance from Same Quarter Last Year` <0, ~ `Variance from Same Quarter Last Year`, color = "red") %>%
   
   color(~ `All Departments Variance from Last Quarter` >0, ~ `All Departments Variance from Last Quarter`, color = "#00b800") %>%
   color(~ `All Departments Variance from Last Quarter` <0, ~ `All Departments Variance from Last Quarter`, color = "red") %>%
   color(~ `All Departments Variance from Same Quarter Last Year` >0, ~ `All Departments Variance from Same Quarter Last Year`, color = "#00b800") %>%
   color(~ `All Departments Variance from Same Quarter Last Year` <0, ~ `All Departments Variance from Same Quarter Last Year`, color = "red") %>%
   width(j = c(1), width = 1.8) %>%
   width(j = c(2), width = 1.5) %>%
   width(j = c(3:length(payer_mix_var_merged)), width = 1.6) %>%
   height(height = .4, part = "body")
   # rotate(j = c(3:length(payer_mix)), rotation = "lrtb", align = "bottom", part = "header")
 
 return(tbl_output)

}

```


```{r Metrics Overview Output, echo = FALSE, warning = FALSE, message = FALSE}

metrics_overview_tbl <- function(department){
# department <- "Cardiovascular Institute/Cardiology"
    # Median Time to New Appointment
  waitTime_mshs_summary <- waitTime_mshs %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    filter(New.PT2 == "New") %>%
    dplyr::select(med_wait) %>%
    mutate(med_wait = as.numeric(med_wait))
  
  waitTime_site_summary <- waitTime_site %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    filter(New.PT2 == "New") %>%
    mutate(med_wait = as.numeric(med_wait)) %>%
    pivot_wider(names_from = Campus,
                values_from = med_wait,
                values_fill = NA) %>%
    dplyr::select(-New.PT2)
  
  waitTime_overall <- merge(waitTime_mshs_summary, waitTime_site_summary)
  waitTime_overall <- waitTime_overall %>% 
      rename(Quarter = Appt.Made.YearQtr,
             Overall = med_wait) %>%
    mutate(Metric = "waitTime")
  
  # New Patients Scheduled <=14 days 
  newPTs_mshs <- waitTime_dist_specialty %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    filter(New.PT2 == "New") %>% 
    group_by(Specialty, Appt.Made.YearQtr, New.PT2, group) %>%
    summarise(total = sum(total)) %>%
    mutate(new_perc = round(total/sum(total),2)) %>%
    filter(group %in% c("0-7","8-14")) %>%
    group_by(Specialty, Appt.Made.YearQtr) %>%
    summarise(new_perc = sum(new_perc)*100)
  
  newPTs_site <- waitTime_dist_site %>%
    filter(Campus %!in% c("MSDD","NETWORK")) %>%
    filter(Specialty == department) %>%
    filter(Appt.Made.YearQtr %in% reporting_YearQtr) %>%
    filter(New.PT2 == "New") %>% 
    group_by(Specialty, Campus, Appt.Made.YearQtr, New.PT2, group) %>%
    summarise(total = sum(total)) %>%
    mutate(new_perc = round(total/sum(total),2)) %>%
    filter(group %in% c("0-7","8-14")) %>%
    group_by(Specialty, Campus, Appt.Made.YearQtr) %>%
    summarise(new_perc = sum(new_perc)*100) %>%
    pivot_wider(names_from = Campus,
                values_from = new_perc)
  
  newPTs_overall <- merge(newPTs_mshs, newPTs_site)
  newPTs_overall <- newPTs_overall %>% 
      rename(Quarter = Appt.Made.YearQtr,
             Overall = new_perc) %>%
      mutate(Metric = "newPTs")
  
  
  # Quarterly Volume Change
  vol_var_mshs <- monthly_vol %>%
      filter(Campus %!in% c("MSDD","NETWORK")) %>%
      filter(Specialty == department) %>%
      filter(Visit.Method == "Total") %>%
      filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)], data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
      mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
      group_by(Specialty, Appt.YearQtr) %>%
      summarise(total = sum(monthly_vol)) %>%
      pivot_wider(names_from = Appt.YearQtr,
                  values_from = total) %>%
      mutate(var_last_qrt = round((.[[4]]/.[[3]])-1,2)*100,
             var_last_yr = round((.[[4]]/.[[2]])-1,2)*100) %>%
      pivot_longer(5:6,
                   names_to = "Metric",
                   values_to = "Overall") %>%
      dplyr::select(Specialty, Metric, Overall)
    
    vol_var_site <- monthly_vol %>%
      filter(Campus %!in% c("MSDD","NETWORK")) %>%
      filter(Specialty == department) %>%
      filter(Visit.Method == "Total") %>%
      filter(Appt.YearQtr %in% c(data_quarters[length(data_quarters)], data_quarters[length(data_quarters)-1], data_quarters[length(data_quarters)-4])) %>%
      mutate(Appt.YearQtr = as.character(Appt.YearQtr)) %>%
      group_by(Specialty, Campus, Appt.YearQtr) %>%
      summarise(total = sum(monthly_vol)) %>%
      pivot_wider(names_from = Appt.YearQtr,
                  values_from = total) 
    
    vol_var_site$var_last_qrt <- round((vol_var_site[[5]]/vol_var_site[[4]])-1,2)*100
    vol_var_site$ var_last_yr <- round((vol_var_site[[5]]/vol_var_site[[3]])-1,2)*100  
    
    vol_var_site <- vol_var_site %>%
      dplyr::select(Specialty, Campus, var_last_qrt, var_last_yr) %>%
      pivot_longer(c("var_last_qrt","var_last_yr"),
                   names_to = "Metric",
                   values_to = "Values") %>%
      pivot_wider(names_from = "Campus",
                  values_from = "Values",
                  values_fill = NA)
    
    vol_var_overall <- merge(vol_var_mshs, vol_var_site)
    
    # Referrals Conversion Rate
    conversion_data <- monthly_referral_vol %>%
      filter(Campus %!in% c("MSDD","NETWORK")) %>%
      filter(Specialty == department) %>%
      filter(Received.YearQtr %in% reporting_YearQtr) 
      
    
    conversion_rate_mshs <- conversion_data %>%
      mutate(Campus = "Overall") %>%
      group_by(Campus, ApptStatusFinal) %>%
      summarise(total = sum(total)) %>%
      group_by(Campus) %>%
      pivot_wider(names_from = ApptStatusFinal,
                  values_from = total, 
                  values_fill = 0) %>%
      mutate(Total = rowSums(across(where(is.numeric)))) %>%
      mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
             `Completion Rate` = round(Arrived/Total,2)*100) %>%
      dplyr::select(Campus, `Conversion Rate`) %>%
      pivot_wider(names_from = Campus,
                  values_from = `Conversion Rate`)
    
    conversion_rate_site <- conversion_data %>%
      group_by(Campus, ApptStatusFinal) %>%
      summarise(total = sum(total)) %>%
      group_by(Campus) %>%
     pivot_wider(names_from = ApptStatusFinal,
                 values_from = total, 
                 values_fill = 0) %>%
     mutate(Total = rowSums(across(where(is.numeric)))) %>%
     mutate(`Conversion Rate` = round((Total - Pending)/Total,2)*100,
            `Completion Rate` = round(Arrived/Total,2)*100) %>%
     dplyr::select(Campus, `Conversion Rate`) %>%
     pivot_wider(names_from = Campus,
                values_from = `Conversion Rate`) 
  
  
  conversion_rate_all <- cbind(conversion_rate_mshs, conversion_rate_site)
  conversion_rate_all$Metric <- "Conversion"
    
    
    # % Physicians >=P50
    P50_mshs <- productivity_raw %>%
      mutate(temp_site = ifelse(Site == "MSW/MSM", "MSW", Site)) %>%
      mutate(temp_site = ifelse(temp_site == "MSH", "MSH-MSDFP", temp_site)) %>%
      filter(`Master Dept` %!in% c("BIMG","MS DOCS","West Care/ West Park","HUDSON YARDS","MANHASSET")) %>%
      filter(!is.na(`Master Dept`)) %>%
      filter(Specialty == department) %>%
      filter(`2022 Reported CFTE` >=0.25) %>%
      dplyr::select(temp_site, NPI, Physician, `2022 Calculate %`) %>%
      distinct() %>%
      mutate(group = ifelse(`2022 Calculate %` >=.50, "Yes","No")) %>%
      group_by(group) %>%
      summarise(total = n()) %>%
      mutate(Overall = round(total/sum(total),2)*100) %>%
      filter(group == "Yes") %>%
      dplyr::select(-c(total,group)) 

    P50_site <- productivity_raw %>%
      mutate(temp_site = ifelse(Site == "MSW/MSM", "MSW", Site)) %>%
      mutate(temp_site = ifelse(temp_site == "MSH", "MSH-MSDFP", temp_site)) %>%
      filter(`Master Dept` %!in% c("BIMG","MS DOCS","West Care/ West Park","HUDSON YARDS","MANHASSET")) %>%
      filter(!is.na(`Master Dept`)) %>%
      filter(Specialty == department) %>%
      filter(`2022 Reported CFTE` >=0.25) %>%
      dplyr::select(temp_site, NPI, Physician, `2022 Calculate %`) %>%
      distinct() %>%
      mutate(group = ifelse(`2022 Calculate %` >=.50, "Yes","No")) %>%
      group_by(temp_site, group) %>%
      summarise(total = n()) %>%
      group_by(temp_site) %>%
      mutate(Overall = round(total/sum(total),2)*100) %>%
      filter(group == "Yes") %>%
      rename(Site = temp_site) %>%
      dplyr::select(Site, Overall) %>%
      pivot_wider(names_from = Site,
                  values_from = Overall)
    
    p50_overall <- merge(P50_mshs, P50_site)
    p50_overall <- p50_overall %>%
      mutate(Metric = "p50")
    
    
    # % Physicians >=P75
    P75_mshs <- productivity_raw %>%
      mutate(temp_site = ifelse(Site == "MSW/MSM", "MSW", Site)) %>%
      mutate(temp_site = ifelse(temp_site == "MSH", "MSH-MSDFP", temp_site)) %>%
      filter(`Master Dept` %!in% c("BIMG","MS DOCS","West Care/ West Park","HUDSON YARDS","MANHASSET")) %>%
      filter(!is.na(`Master Dept`)) %>%
      filter(Specialty == department) %>%
      filter(`2022 Reported CFTE` >=0.25) %>%
      dplyr::select(temp_site, NPI, Physician, `2022 Calculate %`) %>%
      distinct() %>%
      mutate(group = ifelse(`2022 Calculate %` >=.75, "Yes","No")) %>%
      group_by(group) %>%
      summarise(total = n()) %>%
      mutate(Overall = round(total/sum(total),2)*100) %>%
      filter(group == "Yes") %>%
      dplyr::select(-c(total,group)) 
    
    
    # Physicians Above >=P75
    P75_site <- productivity_raw %>%
      mutate(temp_site = ifelse(Site == "MSW/MSM", "MSW", Site)) %>%
      mutate(temp_site = ifelse(temp_site == "MSH", "MSH-MSDFP", temp_site)) %>%
      filter(`Master Dept` %!in% c("BIMG","MS DOCS","West Care/ West Park","HUDSON YARDS","MANHASSET")) %>%
      filter(!is.na(`Master Dept`)) %>%
      filter(Specialty == department) %>%
      filter(`2022 Reported CFTE` >=0.25) %>%
      dplyr::select(temp_site, NPI, Physician, `2022 Calculate %`) %>%
      distinct() %>%
      mutate(group = ifelse(`2022 Calculate %` >=.75, "Yes","No")) %>%
      group_by(temp_site, group) %>%
      summarise(total = n()) %>%
      group_by(temp_site) %>%
      mutate(Overall = round(total/sum(total),2)*100) %>%
      filter(group == "Yes") %>%
      rename(Site = temp_site) %>%
      dplyr::select(Site, Overall) %>%
      pivot_wider(names_from = Site,
                  values_from = Overall)
    
    p75_overall <- merge(P75_mshs, P75_site)
    p75_overall <- p75_overall %>%
      mutate(Metric = "p75")
    
    
    metrics_merged <- bind_rows(waitTime_overall, newPTs_overall, vol_var_overall, conversion_rate_all, p50_overall, p75_overall)
    metrics_merged <- metrics_merged %>%
      dplyr::select(-c(Campus.Specialty.Group, Campus.Specialty.SubGroup, Specialty, Quarter))
    
    # Metrics Overview Table Output ----------------------------------------------  
  overview_tbl <- data.frame(
    Metric = c("waitTime",
              "newPTs",
              "var_last_qrt",
              "var_last_yr",
              "Conversion",
              "p50",
              "p75",
              "Space_Turn",
              "Space_Duration"),
    `Metric Group` = c(rep("Access & Volume",4),
                       rep("Referrals", 1),
                       rep("Physician Productivity", 2),
                       rep("Space", 2)),
    `Metric Name` = c("Median Time to New Appointment",
              "% of New Patients Scheduled <=14 Days",
              "% Volume Increase/Decrease from Prior Quarter",
              "% Volume Increase/Decrease from Same Quarter Last Year",
              "% of Referrals Converted to Scheduled Appointments",
              "% of Physicians Above P50",
              "% of Physicians Above P75",
              "% Space Utilization (By Turns)",
              "% Space Utilization (By Duration)"),
    Benchmark = c("14 days",
                  "80%",
                  "TBD",
                  "TBD",
                  "TBD",
                  "100%",
                  "100%",
                  "85%",
                  "85%")
  )
    
  overview_tbl <- left_join(overview_tbl, metrics_merged, by = "Metric")

  # Format table output 
  tbl_output <- 
    overview_tbl %>%
    arrange(factor(Metric.Group, levels = c("Access & Volume","Referrals", 
                                            "Physician Productivity",
                                            "Space"))) %>%
    dplyr::select(-Metric) %>%
    rename(Metric = Metric.Group) %>%
    flextable() %>%
    autofit() %>%
    merge_v(j = ~Metric) %>%
    merge_at(j = c(1:2), part = "header") %>%
    fontsize(size = 12, part = "all") %>%
    font(fontname = "Calibri", part = "all") %>%
    hline(border = fp_border(color="grey", width = 2), part="header") %>%
    hline_bottom(border = fp_border(color="grey", width = 2), part="all") %>%
    vline(j = 3, border = fp_border(color="grey", width = 0.5), part="body") %>%
    hline(i = c(4,5,7), border = fp_border(color="grey", width = 2), part="body") %>%
    fix_border_issues() %>%
    bold(j = c(1:(length(overview_tbl)-1)), part = "header") %>%
    bold(j = 1, part = "all") %>%
    # surround(border.bottom = fp_border(color = "gray"), part = "all") %>%
    # surround(i = 1, border.bottom = fp_border(color = "black"), part = "header") %>%
    # surround(j = c(3:(length(overview_tbl)-1)), border.left = fp_border(color = "gray"), part = "all") %>%
    colformat_double(
     j = c(4:(length(overview_tbl)-1)),
     i = c(2:nrow(overview_tbl)),
     digits = 0,
     suffix = "%") %>%
    colformat_double(
     j = c(4:(length(overview_tbl)-1)),
     i = c(1),
     digits = 0,
     suffix = " days") %>%
    align(j = c(3:(length(overview_tbl)-1)), align = "center", part = "all") %>%
    align(j = c(1:(length(overview_tbl)-1)), align = "center", part = "header") %>%
    bg(j = c(1:3), bg = "#212070", part = "header") %>%
    bg(j = c(4:(length(overview_tbl)-1)), bg = "#d80b8c", part = "header") %>%
    color(j = c(1:(length(overview_tbl)-1)), color = "white", part = "header") %>%
    color(j = 2, color = "#212070", part = "header") %>%
    width(j = 1, width = 1) %>%
    width(j = 2, width = 2.2) %>%
    width(j = c(4:(length(overview_tbl)-1)), width = 1.1) %>%
    height(height = 0.5, part = "body") 
    # style(i = 1 < 14, 
    #       ~ Overall + MSBI + `MSH- AMBULATORY CARE` + `MSH-MSDFP` + MSM + MSUS + MSW,
    #       pr_t = fp_text(color = "red", italic = TRUE, bold = TRUE)) %>%
    

}
  
```


```{r Action Plan Table Output, echo = FALSE, warning = FALSE, message = FALSE}

`Focus` = c(rep("Access & Volume",3),  rep("Referrals",3),
            rep("Productivity & Recruitment",3),
                   rep("Space",3), rep("Finance",3))
`Initiative` = c(rep("",15))
`Goals` = c(rep("",15))
Status = c(rep("",15))

actionPlan_output <- data.frame(`Focus`, `Initiative`,
                                `Goals`, Status)

actionPlan_output <- actionPlan_output %>%
  flextable() %>%
  autofit() %>%
  fontsize(size = 14, part = "all") %>%
  font(fontname = "Calibri", part = "all") %>%
  bold(j = 1, part = "all") %>%
  bold(j = c(1:4), part = "header") %>%
  merge_v(j = ~Focus) %>%
  set_header_labels(Focus = "Focus Area", Initiative = "Initiative Description", 
                    Goals = "Goals & Challenges", Status = "Status") %>%
  surround(border.bottom = fp_border(color = "gray"), part = "all") %>%
  surround(i = 1, border.bottom = fp_border(color = "black"), part = "header") %>%
  bg(j = c(2:4), bg = "#212070", part = "header") %>%
  color(j = c(2:4), color = "white", part = "header") %>%
  width(j = 1, width = 2) %>%
  width(j = c(2:3), width = 4.7) %>%
  width(j = 4, width = 1.5) %>%
  height(height = 0.35, part = "body")

```


```{r Metric Definitions, echo = FALSE, warning = FALSE, message = FALSE}

metrics_def <- data.frame(Metric = c("Net Operating Variance to Budget",
                                     "Patient Revenue Variance to Budget",
                                     "Expense Variance to Budget",
                                     "Physician Productivity",
                                     "Time to Appointment",
                                     "Referrals - Conversion Rate",
                                     "Referrals - Completion Rate",
                                     "Average Weekday Visits",
                                     "Variance from Benchmark",
                                     "% Utilization (By Turns)",
                                     "% Utilization (By Durations)",
                                     "Average Utilization by Hour"),
                          Definition = c("Difference between an actual surplus (or deficit) and a budgeted surplus (or deficit).",
                                         "Difference between actual patient revenue and budgeted patient revenue",
                                         "Difference between actual expense and budgeted expense",
                                         "A measure of the amount of patient care services provided, based on total worked",
                                         "Number of days between date-of-schedule and date-of-service.",
                                         "Percent of total number of appointments scheduled over total number of referrals received",
                                         "Percent of total number of arrived appointments over total number of referrals received.",
                                         "Total number of arrived visits over total number of business days in a time period.",
                                         "Difference between Average Weekday Volume and Expected Daily Volume Target based on total room count and visits/room/day benchmark (i.e. 10 rooms available per day and 10 visits/room/day benchmark equals to 100 expected daily volume target; 120 average weekday volume results in 20 Volume Variance to Benchmark).",
                                         "Average weekday volume over total number of rooms available over visits/room/day benchmark.",
                                         "Total sum of scheduled visit durations with 20% adjustment factor over total room time available. Total room time available is calculated based on Total Rooms Available per Day x Total Working Hours per Day (10 rooms available per day x 8 working hours per day = 80 hours of room time available per day).",
                                         "Total sum of scheduled visit durations with 20% adjustment factor over total room time available within the respective hour (2 30-minute visits scheduled at 9:00am and 9:30am with 1 rooms available = 60 minutes of visit duration / 60 room time available = 100% Utilization)."))


metrics_def_tbl <- flextable(metrics_def) %>%
  fontsize(size = 12, part = "all") %>%
  font(fontname = "Calibri", part = "all") %>%
  autofit() %>%
  bold(j = 1, part = "all") %>%
  bold(i = 1, part = "header") %>%
  bg(j = c(1:length(metrics_def)), bg = "#212070", part = "header") %>%
  color(j = c(1:length(metrics_def)), color = "white", part = "header") %>%
  border_inner_h(border = fp_border_default(width = 1, color = "lightgrey"), part="all") %>%
  # surround(i = 1, border.bottom = fp_border(color = "white"), part = "all") %>%
  width(j = 1, 3) %>%
  width(j = 2, 9) 


```


```{r Quarterly Performance Report PPT Ouput, ft.align = "center", echo = FALSE, warning = FALSE, message = FALSE}

specialties <- c(
  "Anesthesiology/Pain Management",
  "Cardiovascular Institute/Cardiology",
  "Cardiovascular Surgery",
  "Dermatology",
  # "Genetics & Genomic Sciences",
  "Geriatrics",
  "Medicine - Clinical Immunology",
  "Medicine - Endocrinology",
  "Medicine - Gastroenterology",
  "Medicine - Infectious Diseases/Travel Medicine",
  "Medicine - Liver",                              
  "Medicine - Primary Care",
  "Medicine - Pulmonary/Sleep",
  "Medicine - Renal/Nephrology",
  "Medicine - Rheumatology",
  "Neurology",
  "Neurosurgery",
  "OB-GYN",
  "Ophthalmology",
  "Orthopedics",
  "Otolaryngology",
  # "Pathology",
  "Pediatrics",
  "Psychiatry",
  # "Radiology",
  "Rehabilitation and Human Performance",
  "Surgery",
  "Thoracic Surgery",
  "Tisch Institute/Hematology Oncology",
  "Transplant Institute",
  # "Urgent Care",
  "Urology"
  )


for(i in specialties){
  
  i <- "Surgery"

  # Import in pptx template
  ppt_temp <- read_pptx("template_performanceReport.pptx")
    
    # 1. Create Title Slide --------------------------------------------------------
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title Slide", master = "Default Theme")
  ppt_temp  <- ph_with(ppt_temp, value = paste0("Quarterly Finance & Operational Performance Report"), 
                       location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <-  ph_with(ppt_temp, value = as.character(reporting_YearQtr), 
                       location = ph_location_label(ph_label = "Subtitle 2"))
  ppt_temp <-  ph_with(ppt_temp, value = i, 
                       location = ph_location_label(ph_label = "Text Placeholder 6"))
    
    # 2. Create Volume & Access Slide -----------------------------------------------
  ## Section Header 
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Section Header", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Volume & Access",
                      location = ph_location_label(ph_label = "Title 1"))
  
  ## Volume Metrics Slide ========================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "1_Two Vertical Tables", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, paste0(reporting_YearQtr," ", "Volume"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = dept_monthly_vol_function(i),
                      location = ph_location_label(ph_label = "Chart Placeholder 6"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; total volume excludes MSDD and NETWORK.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  ### Generate Volume Heat Map Title
  text_style <- fp_text(font.size = 16, bold = TRUE, font.family = "Calibri")
  par_style <- fp_par(text.align = "center")
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Volume by Geography", prop = text_style), fp_p = par_style),  
                      location = ph_location_label(ph_label = "Text Placeholder 7"))
  ### Generate and save volume heat map 
  dept_heat_map_function(i) 
  ppt_temp <- ph_with(ppt_temp, value = external_img(src = "vol_heat_map.png", height = 1.06/2, width = 1.39/2),
                      location = ph_location_label(ph_label = "Table Placeholder 9"))
  
  ### Key Takeaways 
  vol_slide_takeaways <- block_list(fpar(ftext(paste0("Total volume for ",reporting_YearQtr," was ",dept_monthly_vol_takeaway(i)[2],
                                                      " (",dept_monthly_vol_takeaway(i)[1]," was in-person visits)"),
                                               prop = fp_text(font.family = 'Calibri',font.size=16, bold = TRUE))),
                                    fpar(ftext(paste0("Average monthly volume for this quarter was ",dept_monthly_vol_takeaway(i)[3]),
                                               prop = fp_text(font.family = 'Calibri',font.size=14))),
                                    fpar(ftext(paste0("This is ",dept_monthly_vol_takeaway(i)[4]," change from last quarter (total MSHS change: ",
                                                      dept_monthly_vol_takeaway(i)[9],"; median change across all departments: ",
                                                      dept_monthly_vol_takeaway(i)[11],")"),
                                               prop = fp_text(font.family = 'Calibri',font.size=14))),
                                    fpar(ftext(paste0("This is ",dept_monthly_vol_takeaway(i)[5]," change from same quarter last year (total MSHS change: ",
                                                      dept_monthly_vol_takeaway(i)[10],"; median change across all departments: ", 
                                                      dept_monthly_vol_takeaway(i)[12],")"),
                                               prop = fp_text(font.family = 'Calibri',font.size=14))),
                                    fpar(ftext(paste0(dept_monthly_vol_takeaway(i)[6]," saw the largest volume with ",dept_monthly_vol_takeaway(i)[7],
                                                      " visits (",dept_monthly_vol_takeaway(i)[8]," of total volume)"),
                                               prop = fp_text(font.family = 'Calibri',font.size=14))))
  
  
  ppt_temp <- ph_with(ppt_temp, value = vol_slide_takeaways,  
                      location = ph_location_label(ph_label = "Text Placeholder 3"),
                      level_list = c(1,2,2,2,2)) 
  
  
  ## Volume Trending by Site Slide ===============================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Volume_Trending", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0("Volume Trending - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  # ppt_temp <- ph_with(ppt_temp, value = deptSite_monthly_vol_function(i),
  #                     location = ph_location_label(ph_label = "Chart Placeholder 6"))
  ppt_temp <- ph_with(ppt_temp, value = deptSite_monthly_vol_function_1(i),
                      location = ph_location_label(ph_label = "Chart Placeholder 6"))
  ppt_temp <- ph_with(ppt_temp, value = deptSite_monthly_vol_function_2(i),
                      location = ph_location_label(ph_label = "Table Placeholder 9"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only; metrics do not account for any data prior to Epic go-live.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  
  ## Access Metrics Slide ========================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Two Vertical Tables", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Access"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = overall_time_to_appt_dist_function(i),
                      location = ph_location_label(ph_label = "Chart Placeholder 6"))
  ppt_temp <- ph_with(ppt_temp, value = site_time_to_appt_function(i),
                      location = ph_location_label(ph_label = "Table Placeholder 9"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; Wait Time is total days from appointment scheduled to date of service (including weekends); Time to Appointment Horizon excludes MSDD and NETWORK.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  ### Key Takeaways 
  access_slide_takeaways <- block_list(fpar(ftext(paste0("Total new patient visits scheduled in ",reporting_YearQtr," was ",dept_access_takeaway(i)[1],
                                                         " (",dept_access_takeaway(i)[2]," of total visits scheduled)"),
                                                  prop = fp_text(font.family = 'Calibri',font.size=16, bold = TRUE))),
                                       fpar(ftext(paste0(dept_access_takeaway(i)[3],
                                                         " of new in-office ",i,
                                                         " patients are scheduled within 14 days (total MSHS: ",
                                                         dept_access_takeaway(i)[7],"; median across all departments: ",
                                                         dept_access_takeaway(i)[10],")"),
                                                  prop = fp_text(font.family = 'Calibri',font.size=14))),
                                       fpar(ftext(paste0(dept_access_takeaway(i)[4],
                                                         " of new telehealth ",i,
                                                         " patients are scheduled within 14 days (total MSHS: ",
                                                         dept_access_takeaway(i)[8],"; median across all departments: ",
                                                         dept_access_takeaway(i)[11],")"),
                                                  prop = fp_text(font.family = 'Calibri',font.size=14))),
                                       fpar(ftext(paste0("Median wait time for new ",i," patients across all sites is ",
                                                         dept_access_takeaway(i)[5], " days"),
                                                  prop = fp_text(font.family = 'Calibri',font.size=14))))
  
  
   # key_list <- list(new_pt_vol, new_pt_vol_perc, new_inPerson_14days, new_tele_14days, dept_med_waitTime,
   #                 mshs_new_pt_vol_perc, mshs_new_inPerson_14days,  mshs_new_tele_14days,
   #                 specialty_new_pt_vol_perc, specialty_new_inPerson_14days, specialty_new_tele_14days)
  
  
  ppt_temp <- ph_with(ppt_temp, value = access_slide_takeaways,  
                      location = ph_location_label(ph_label = "Text Placeholder 3"),
                      level_list = c(1,2,2,2)) 
  
  ## Referrals Metric Slide ========================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Referrals_Slide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Referral"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = conversion_rate_function(i),
                      location = ph_location_label(ph_label = "Chart Placeholder 6"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only; metrics do not account for any data prior to Epic go-live; Conversion Rate is percent of scheduled appointments over referrals received; Completion Rate is percent of arrived appointments over referrals received.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  
  ## 3. Create Productivity Metrics Slide ==========================================
  ## Create Section Header
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Section Header", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Physician Productivity",
                      location = ph_location_label(ph_label = "Title 1"))
  
  ### Productivity Overview
  # ppt_temp <- ppt_temp %>%
  #   add_slide(layout = "productivity_Slide", master = "Default Theme")
  # ppt_temp <- ph_with(ppt_temp, value = paste0("Physician Productivity Overview - ",i), 
  #                     location = ph_location_label(ph_label = "Title 1"))
  # ppt_temp <- ph_with(ppt_temp, value = productivity_scatter_function(i),
  #                     location = ph_location_label(ph_label = "Chart Placeholder 6"))
  #### Generate Volume Median Wait Time vs. Productivity Table
  # text_style <- fp_text(font.size = 16, bold = TRUE, font.family = "Calibri")
  # par_style <- fp_par(text.align = "center")
  # ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Count of Providers by Time to Appointment vs. % Productivity", prop = text_style), fp_p = par_style),  
  #                     location = ph_location_label(ph_label = "Text Placeholder 7"))
  # ppt_Temp <- ph_with(ppt_temp, value = productivity_table_function(i),
  #                     location = ph_location_label(ph_label = "Table Placeholder 9"))
  
  ### Productivity by Provider 
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Physicians Below P50"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = productivity_provider_50_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Productivity and charges data as of 8/12/2022; 2021 and 2022 Calculate %'s based on Jan-Jun annualized data; excludes providers with reported cFTE below 0.25.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value =paste0(reporting_YearQtr," ", "Physicians P50-74"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = productivity_provider_75_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
 ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Productivity and charges data as of 8/12/2022; 2021 and 2022 Calculate %'s based on Jan-Jun annualized data; excludes providers with reported cFTE below 0.25.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Physicians Above P75"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = productivity_provider_100_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Productivity and charges data as of 8/12/2022; 2021 and 2022 Calculate %'s based on Jan-Jun annualized data; excludes providers with reported cFTE below 0.25.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  
  # 4. Space Utilization ---------------------------------------------------------
  ## Create Section Header
  # ppt_temp <- ppt_temp %>%
  #   add_slide(layout = "Section Header", master = "Default Theme")
  # ppt_temp <- ph_with(ppt_temp, value = "Space Utilization",
  #                     location = ph_location_label(ph_label = "Title 1"))
  
  ## Create Utilization Slide ===================================================
  ### Utilization Overall and by Site
  # ppt_temp <- ppt_temp %>%
  #   add_slide(layout = "Utilization_Slide", master = "Default Theme")
  # ppt_temp <- ph_with(ppt_temp, value = paste0("Overall Utilization - ",i), 
  #                     location = ph_location_label(ph_label = "Title 1"))
  # ppt_temp <- ph_with(ppt_temp, value = overall_day_util_tbl_function(i),
  #                     location = ph_location_label(ph_label = "Chart Placeholder 6"))
  # text_style <- fp_text(font.size = 9, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  # par_style <- fp_par(text.align = "left", padding.bottom = 5)
  # ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("% Utilization by Turns is average weekday volume over total number of rooms available over visits/room/day benchmark specified for each department; % Utilization by Durations is total sum of scheduled visit durations with 20% adjustment factor/buffer over total room time available.", 
  #                                                  prop = text_style), fp_p = par_style),  
  #                     location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  
  ### Utilization by Hour - Weekdays
  # ppt_temp <- ppt_temp %>%
  #   add_slide(layout = "Two Vertical Tables", master = "Default Theme")
  # ppt_temp <- ph_with(ppt_temp, value = paste0("Utilization by Hour - ",i), 
  #                     location = ph_location_label(ph_label = "Title 1"))
  # ppt_Temp <- ph_with(ppt_temp, value = overall_weekday_util_hour(i),
  #                     location = ph_location_label(ph_label = "Chart Placeholder 6"))
  # ppt_Temp <- ph_with(ppt_temp, value = site_weekday_util_hour(i),
  #                     location = ph_location_label(ph_label = "Table Placeholder 9"))
  
  
  # 5. Create Finance Slide ------------------------------------------------------
  ## Create Section Header
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Section Header", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Finance",
                      location = ph_location_label(ph_label = "Title 1"))
  
  ## Create Finance Metrics Slide ================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0("Finance - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  
  ## Create Payer Mix by Site Slide ==============================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Payer_Mix_Slide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Payer Mix"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = dept_payer_mix(i),
                      location = ph_location_label(ph_label = "Chart Placeholder 6"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only; metrics do not account for any data prior to Epic go-live; payer mix based on coverage associated to completed visits, not charges.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  
  
  # 6. Create Metrics Overview/Action Plan Slide -------------------------------
  ## Section Header ============================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Section Header", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Metrics Overview & Action Plan",
                      location = ph_location_label(ph_label = "Title 1"))
  
  # 2. Add Improving Access Slide ==============================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Diagram", master = "Default Theme")
  ppt_temp  <- ph_with(ppt_temp, value = paste0("Improving Access"), 
                       location = ph_location_label(ph_label = "Title 1"))

  ## Metrics Overview Table ====================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Center", master = "Default Theme")
  ppt_temp <- ppt_temp %>% 
    ph_with(value = paste0(reporting_YearQtr," ", "Metrics Overview"," - ",i), 
            location = ph_location_label(ph_label = "Title 1")) 
  ppt_temp <- ph_with(ppt_temp, value = metrics_overview_tbl(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; Overall metric excludes MSDD and NETWORK; physician productivity site mappings are based on cFTE attribution (MSW/MSM providers mapped to MSW, MSUS providers mapped to MSBI, and MSH providers mapped to MSH-MSDFP).",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))
  

  ## Action Plan Table =========================================================
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Action_Plan_Slide", master = "Default Theme")
  ppt_temp <- ppt_temp %>% 
    ph_with(value = paste0(reporting_YearQtr," ", "Action Plan"," - ",i), 
            location = ph_location_label(ph_label = "Title 1")) 
  ppt_Temp <- ph_with(ppt_temp, value = actionPlan_output,
                      location = ph_location_label(ph_label = "Content Placeholder 8"))
  
  
  # 7. Create Appendix Slide ----------------------------------------------------
  ## Section Header 
 ppt_temp <- ppt_temp %>%
    add_slide(layout = "Section Header", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Appendix",
                      location = ph_location_label(ph_label = "Title 1"))
  
  ## Productivity vs. Access by Provider
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Access vs. Below P50"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = access_provider_50_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; based on productivity data as of 8/12/2022; physician productivity site mappings are based on cFTE attribution (MSW/MSM providers mapped to MSW, MSUS providers mapped to MSBI, and MSH providers mapped to MSH-MSDFP).",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))

  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Access vs. P50-74"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = access_provider_75_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; based on productivity data as of 8/12/2022; physician productivity site mappings are based on cFTE attribution (MSW/MSM providers mapped to MSW, MSUS providers mapped to MSBI, and MSH providers mapped to MSH-MSDFP).",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))

  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Wide", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = paste0(reporting_YearQtr," ", "Access vs. Above P75"," - ",i), 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = access_provider_100_function(i),
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  text_style <- fp_text(font.size = 10, italic = TRUE, color = "#7f7f7f", font.family = "Calibri")
  par_style <- fp_par(text.align = "left", padding.bottom = 5)
  ppt_temp <- ph_with(ppt_temp, value = fpar(ftext("Includes Epic data only - metrics do not account for any data prior to Epic go-live; based on productivity data as of 8/12/2022; Access vs. Productivity provides median wait time to new appointment at each site and practice by physician.",
                                                   prop = text_style), fp_p = par_style),
                      location = ph_location_label(ph_label = "Footer Placeholder 4"))

  ## Utilization by Hour - Weekends
  # ppt_temp <- ppt_temp %>%
  #   add_slide(layout = "Two Vertical Tables", master = "Default Theme")
  # ppt_temp <- ph_with(ppt_temp, value = paste0("Utilization by Hour (Weekends) - ",i),
  #                     location = ph_location_label(ph_label = "Title 1"))
  # ppt_temp <- ph_with(ppt_temp, value = overall_weekend_util_hour(i),
  #                     location = ph_location_label(ph_label = "Chart Placeholder 6"))
  # ppt_temp <- ph_with(ppt_temp, value = site_weekend_util_hour(i),
  #                     location = ph_location_label(ph_label = "Table Placeholder 9"))
  
  ## Metric Definitions
  ppt_temp <- ppt_temp %>%
    add_slide(layout = "Title and Content_Center", master = "Default Theme")
  ppt_temp <- ph_with(ppt_temp, value = "Metric Definitions", 
                      location = ph_location_label(ph_label = "Title 1"))
  ppt_temp <- ph_with(ppt_temp, value = metrics_def_tbl,
                      location = ph_location_label(ph_label = "Content Placeholder 2"))
  
  
  # Compiled Slide Output --------------------------------------------------------
  dir <- "C:/Users/kweons01/Desktop/Strategic Initiatives - So Youn/Github/performance-report/Q2 2022 Reports/"
  print(ppt_temp, target=paste0(dir,paste0(reporting_YearQtr, "_Performance Report_", gsub("/", "_", i),".pptx")))
  
}


```
